"use strict";
/* Calendar UI V3 — final renderer for My Performance 2.0. */
(function(){
  const M=window.MyPerformanceCalendarModel,E=window.MyPerformancePlannerEngine;
  if(!M||!E||typeof state==='undefined')return;

  const BUILD='2.0.0';
  const BASE={dashboard:typeof renderDashboard==='function'?renderDashboard:null,quests:typeof renderQuests==='function'?renderQuests:null,timeline:typeof renderTimeline==='function'?renderTimeline:null,player:typeof renderPlayer==='function'?renderPlayer:null,rewards:typeof renderRewards==='function'?renderRewards:null,config:typeof renderConfig==='function'?renderConfig:null};
  const DAYS=['Domingo','Segunda','Terça','Quarta','Quinta','Sexta','Sábado'];
  const short=d=>DAYS[d].slice(0,3);
  const dur=x=>Math.max(0,Number(x?.end||0)-Number(x?.start||0));
  const time=n=>window.MyPerformanceRoutine.toTime(n);
  const groupClass=g=>g==='GSA'?'GSA':g==='Estudos'?'Estudos':'Pessoal';
  const completed=(q,date)=>{try{return done(q,date)}catch{return false}};
  const campaignName=q=>M.campaignForQuest(q)?.name||'';

  function modal(html){document.getElementById('modal').innerHTML=`<div class="modal-backdrop"><div class="modal-card calendar-modal"><button class="modal-close" id="calModalClose">×</button>${html}</div></div>`;document.getElementById('calModalClose').onclick=closeModal}
  function closeModal(){document.getElementById('modal').innerHTML=''}
  function fmtDuration(m){m=Math.max(0,Math.round(m));return m>=60?`${Math.floor(m/60)}h${m%60?` ${m%60}min`:''}`:`${m}min`}
  function dateTitle(date){return fmt(date,{weekday:'long',day:'2-digit',month:'long'})}

  function slotKind(x){if(x.buffer)return'buffer';if(x.fixed)return'fixed';if(x.q?.questType==='main')return'main';return'side'}
  function slotHtml(x,date){
    const q=x.q||{},kind=slotKind(x),isDone=!x.buffer&&completed(q,x.originDate||date),camp=x.campaignName||campaignName(q),deadline=x.deadline||q.dueDate||'',canSkip=x.movable&&!x.fixed&&!x.buffer&&!isDone;
    if(x.buffer)return`<div class="cal-slot buffer"><div class="cal-time"><b>${time(x.start)}</b><span>${time(x.end)}</span></div><div class="cal-slot-body"><div class="cal-title">↔ ${esc(q.title)}</div><div class="cal-note">${esc(x.reason||'buffer logístico')}</div></div></div>`;
    return`<div class="cal-slot ${kind} ${isDone?'done':''} ${x.emergency?'emergency':''}" data-slot-id="${esc(x.id)}">
      <div class="cal-time"><b>${time(x.start)}</b><span>${time(x.end)}</span></div>
      <div class="cal-slot-body">
        <div class="cal-title-row"><div><div class="cal-title">${x.fixed?'🔒 ':x.mainQuest?'◆ ':''}${esc(q.title)}</div><div class="cal-tags"><span class="tag ${groupClass(x.group||q.domain)}">${esc(x.group||q.domain||'Pessoal')}</span>${camp?`<span class="pill amber">${esc(camp)}</span>`:''}<span class="pill">${q.questType==='main'?'MAIN QUEST':'SIDE QUEST'}</span>${deadline?`<span class="pill ${deadline<date&&!isDone?'red':''}">⌛ ${fmt(deadline)}</span>`:''}${x.fixed?'<span class="pill">HORÁRIO FIXO</span>':''}${x.emergency?'<span class="pill red">PRAZO CRÍTICO</span>':''}</div></div><div class="cal-actions">${isDone?'<span class="pill green">Concluída</span>':x.sessionOnly?`<button class="btn small primary" data-session-done="${esc(x.id)}">Registrar sessão</button><button class="mini-link" data-mission-complete="${esc(q.id)}" data-occ="${esc(x.originDate||date)}">Concluir missão</button>`:`<button class="check" data-mission-complete="${esc(q.id)}" data-occ="${esc(x.originDate||date)}">✓</button>`}${canSkip?`<button class="mini-link" data-slot-skip="${esc(x.id)}">Não fiz</button>`:''}${!x.buffer?`<button class="mini-link" data-edit="${esc(q.id)}">Editar</button>`:''}</div></div>
        <div class="cal-note">${esc(x.reason||'planejado')} · ${fmtDuration(dur(x))}${x.sessionOnly?' · sessão de progresso, não encerra a Main Quest':''}</div>
      </div>
    </div>`
  }
  function emptyWindowHtml(g){return`<div class="cal-empty-window"><div><b>${time(g.start)}–${time(g.end)}</b> · ${esc(g.label)}</div><span>${esc(g.groups.join(' + '))} · ${fmtDuration(g.minutes)} livres</span></div>`}

  function bindCalendar(plan,date){
    const byId=new Map((plan.slots||[]).map(x=>[x.id,x]));
    document.querySelectorAll('[data-session-done]').forEach(b=>b.onclick=()=>{const x=byId.get(b.dataset.sessionDone);if(x&&E.recordSession(x,date)){toast('Sessão registrada. Cronograma redistribuído.');render()}});
    document.querySelectorAll('[data-mission-complete]').forEach(b=>b.onclick=()=>{toggleQuest(b.dataset.missionComplete,b.dataset.occ||date)});
    document.querySelectorAll('[data-slot-skip]').forEach(b=>b.onclick=()=>{const x=byId.get(b.dataset.slotSkip);if(!x)return;if(!confirm(`Marcar “${x.q.title}” como não realizada hoje e replanejar o trabalho futuro? O deadline não será alterado.`))return;E.skipSlot(x,date);toast('Missão devolvida ao planejamento');render()});
    if(typeof bindQuestCards==='function')bindQuestCards()
  }

  function renderTodayV3(){
    const date=state.plannerDate||today(),p=E.planDay(date),diag=E.diagnostics(date),view=document.getElementById('view');
    const fixed=p.slots.filter(x=>x.fixed&&!x.buffer).length,main=p.slots.filter(x=>x.mainQuest).length,empty=E.emptyWindows(p),risks=diag.atRisk.filter((r,i,a)=>a.findIndex(x=>x.missionId===r.missionId&&x.deadline===r.deadline)===i).slice(0,5);
    view.innerHTML=`
      <div class="section-title planner-head"><div><span class="eyebrow">CALENDÁRIO INTELIGENTE · v${BUILD}</span><h2>${esc(dateTitle(date))}</h2><p class="muted">Janelas definem capacidade. Missões ocupam o calendário. Horário fixo só existe em compromissos especiais.</p></div><div class="day-nav"><button class="btn small" id="calPrev">←</button><button class="btn small" id="calToday">Hoje</button><button class="btn small" id="calNext">→</button><button class="btn primary small" id="calReplan">↻ Replanejar</button></div></div>
      ${p.discarded?`<div class="callout danger"><b>DIA DESCARTADO</b><p>As missões flexíveis pendentes deste dia voltaram ao backlog. Deadlines permaneceram intactos.</p><button class="btn" id="restoreDiscarded">Restaurar este dia</button></div>`:''}
      ${risks.length?`<div class="callout danger"><b>⚠ Risco real de prazo</b><p>O motor não moveu deadlines. Há trabalho que não cabe integralmente antes do prazo atual.</p>${risks.map(r=>`<div class="statline"><span>${esc(r.title)}</span><b>${fmtDuration(r.remaining)} · ${fmt(r.deadline)}</b></div>`).join('')}</div>`:''}
      <div class="planner-stats"><div class="card mini-stat"><span>Compromissos fixos</span><b>${fixed}</b><small>nunca deslocados</small></div><div class="card mini-stat"><span>Main Quests</span><b>${main}</b><small>distribuídas por prazo + prioridade</small></div><div class="card mini-stat"><span>Janelas livres</span><b>${empty.reduce((n,x)=>n+x.minutes,0)} min</b><small>capacidade ainda disponível</small></div><div class="card mini-stat"><span>Motor</span><b>Calendar V3</b><small>uma única autoridade de planejamento</small></div></div>
      <div class="calendar-toolbar"><button class="btn danger" id="discardCalendarDay" ${p.discarded?'disabled':''}>✕ Descartar dia</button></div>
      <div class="day-timeline calendar-timeline">${p.slots.map(x=>slotHtml(x,date)).join('')||'<div class="empty">Nenhuma missão planejada.</div>'}</div>
      ${p.preempted?.length?`<div class="card"><span class="eyebrow">SIDE QUESTS DESLOCADAS</span><h3>Uma Main Quest precisou usar capacidade excepcional</h3>${p.preempted.map(x=>`<div class="statline"><span>${esc(x.q?.title||'Side Quest')}</span><b>${esc(x.reason||'replanejada')}</b></div>`).join('')}</div>`:''}
      ${empty.length?`<div class="card free-capacity"><span class="eyebrow">CAPACIDADE LIVRE</span><h3>Janelas ainda disponíveis</h3>${empty.map(emptyWindowHtml).join('')}</div>`:''}`;
    document.getElementById('calPrev').onclick=()=>{state.plannerDate=addDays(date,-1);saveState();render()};document.getElementById('calToday').onclick=()=>{state.plannerDate=today();saveState();render()};document.getElementById('calNext').onclick=()=>{state.plannerDate=addDays(date,1);saveState();render()};
    document.getElementById('calReplan').onclick=()=>{toast('Planejamento recalculado com o estado atual');render()};
    document.getElementById('discardCalendarDay').onclick=()=>{if(!confirm('Descartar este dia? Tudo que NÃO foi concluído voltará ao planejamento futuro. Compromissos fixos não mudam de data e nenhum deadline será alterado.'))return;E.discardDay(date);toast('Dia descartado e cronograma futuro recalculado');render()};
    document.getElementById('restoreDiscarded')?.addEventListener('click',()=>{E.restoreDay(date);toast('Dia restaurado');render()});bindCalendar(p,date)
  }

  function campaignCard(c){const count=(c.missionIds||[]).length,doneN=(c.missionIds||[]).filter(id=>{const q=questById(id);return q?hasEverDone(id):false}).length;return`<div class="campaign-card" data-campaign="${esc(c.id)}"><div><span class="eyebrow">PRIORIDADE ${c.priority}</span><h3>${esc(c.name)}</h3><div class="cal-tags"><span class="tag ${groupClass(c.groupId)}">${esc(c.groupId)}</span><span class="pill">${count} missões</span><span class="pill green">${doneN}/${count} concluídas</span></div></div><div class="campaign-actions"><button class="mini-link" data-camp-up="${esc(c.id)}">↑</button><button class="mini-link" data-camp-down="${esc(c.id)}">↓</button><button class="btn small" data-camp-add-mission="${esc(c.id)}">+ Missão</button><button class="btn small" data-camp-export="${esc(c.id)}">Exportar</button><button class="btn small danger" data-camp-delete="${esc(c.id)}">Excluir</button></div></div>`}
  function windowRow(w){return`<div class="window-row"><div class="window-day">${short(w.weekday)}</div><div class="window-time">${time(w.start)}–${time(w.end)}</div><div class="window-main"><b>${esc(w.label)}</b><div class="cal-tags">${w.groups.map(g=>`<span class="tag ${groupClass(g)}">${esc(g)}</span>`).join('')}${w.preferredGroup?`<span class="pill">preferência: ${esc(w.preferredGroup)}</span>`:''}${w.emergencyOnly?'<span class="pill red">só emergência</span>':''}</div></div><div><button class="mini-link" data-window-edit="${esc(w.id)}">Editar</button><button class="mini-link" data-window-delete="${esc(w.id)}">Excluir</button></div></div>`}

  function renderConfigV3(){
    if(BASE.config)BASE.config();else document.getElementById('view').innerHTML='';
    const host=document.getElementById('view'),c=M.model(),fixed=M.fixedMissions();
    host.insertAdjacentHTML('beforeend',`
      <div class="section-title"><div><span class="eyebrow">MY PERFORMANCE 2.0</span><h2>Calendário semanal</h2><p class="muted">Estas são janelas de capacidade, não tarefas engessadas. Uma janela pode aceitar mais de um Grupo.</p></div><button class="btn primary" id="addWindow">+ Janela</button></div>
      <div class="card window-editor">${c.windows.slice().sort((a,b)=>a.weekday-b.weekday||a.start-b.start).map(windowRow).join('')}</div>

      <div class="section-title"><div><span class="eyebrow">COMPROMISSOS ESPECIAIS</span><h2>Recorrências com horário fixo</h2><p class="muted">São missões, não regras do motor. Apenas estas recorrências bloqueiam um horário específico.</p></div></div>
      <div class="card fixed-list">${fixed.map(q=>`<div class="fixed-row"><div><b>🔒 ${esc(q.title)}</b><span>${DAYS[(q.weekdays||[])[0]]||''} · ${esc(q.timeStart)}–${esc(q.timeEnd)}${q.bufferBeforeMin?` · ${q.bufferBeforeMin} min antes`:''}${q.bufferAfterMin?` · ${q.bufferAfterMin} min depois`:''}</span></div><button class="btn small" data-fixed-edit="${esc(q.id)}">Editar missão</button></div>`).join('')}</div>

      <div class="section-title"><div><span class="eyebrow">CAMPANHAS</span><h2>Pacotes de Main Quests</h2><p class="muted">Campanhas agrupam missões e fornecem prioridade ao motor. Grupo = onde a Campanha pode consumir capacidade.</p></div><div><button class="btn" id="importCampaign">Importar Campanha</button> <button class="btn primary" id="addCampaign">+ Campanha</button><input id="campaignFile" type="file" accept="application/json" hidden></div></div>
      <div class="campaign-list">${c.campaigns.map(campaignCard).join('')||'<div class="empty">Nenhuma Campanha.</div>'}</div>

      <div class="section-title"><div><span class="eyebrow">GRUPOS</span><h2>Áreas de capacidade</h2></div></div>
      <div class="grid3">${M.groups().map(g=>`<div class="card"><div class="level-num">${g.icon}</div><h3>${esc(g.name)}</h3><p class="muted">Janelas e Campanhas podem usar este Grupo.</p></div>`).join('')}</div>

      <div class="section-title"><div><span class="eyebrow">MOTOR</span><h2>Políticas globais mínimas</h2><p class="muted">Sem horário de academia, Muay Thai ou regras específicas de atividade.</p></div></div>
      <div class="card"><div class="form-row"><div class="field"><label>Horizonte de planejamento (dias)</label><input id="engineHorizon" type="number" min="14" max="180" value="${Number(c.engine.horizonDays||90)}"></div><div class="field"><label>Margem antes do prazo (dias)</label><input id="engineSafety" type="number" min="0" max="14" value="${Number(c.engine.safetyDays||2)}"></div><div class="field"><label>Sessão máxima (min)</label><input id="engineMaxSession" type="number" min="30" max="240" step="15" value="${Number(c.engine.maxSessionMin||120)}"></div></div><button class="btn primary" id="saveEngine">Salvar políticas</button></div>`);
    bindConfigV3();window.MyPerformanceCloud?.bindUI?.()
  }

  function openWindow(id=''){
    const c=M.model(),w=c.windows.find(x=>x.id===id)||{weekday:1,start:540,end:720,label:'Nova janela',groups:['GSA'],preferredGroup:'GSA',emergencyOnly:false};
    modal(`<span class="eyebrow">JANELA DE CAPACIDADE</span><h2>${id?'Editar':'Adicionar'} janela</h2><div class="field"><label>Dia</label><select id="winDay">${DAYS.map((d,i)=>`<option value="${i}" ${Number(w.weekday)===i?'selected':''}>${d}</option>`).join('')}</select></div><div class="form-row"><div class="field"><label>Início</label><input id="winStart" type="time" value="${time(w.start)}"></div><div class="field"><label>Fim</label><input id="winEnd" type="time" value="${time(w.end)}"></div></div><div class="field"><label>Nome da janela</label><input id="winLabel" value="${esc(w.label)}"></div><div class="field"><label>Grupos permitidos</label><div class="weekdays">${M.groups().map(g=>`<label class="group-check"><input type="checkbox" value="${g.id}" data-win-group ${w.groups.includes(g.id)?'checked':''}> ${g.name}</label>`).join('')}</div></div><div class="field"><label>Grupo preferencial</label><select id="winPreferred"><option value="">Sem preferência</option>${M.groups().map(g=>`<option value="${g.id}" ${w.preferredGroup===g.id?'selected':''}>${g.name}</option>`).join('')}</select></div><label class="setting-toggle"><input type="checkbox" id="winEmergency" ${w.emergencyOnly?'checked':''}><span><b>Só usar em emergência</b><small>Disponível apenas quando um prazo realmente não cabe nas demais janelas.</small></span></label><button class="btn primary" id="saveWindow">Salvar janela</button>`);
    document.getElementById('saveWindow').onclick=()=>{const groups=[...document.querySelectorAll('[data-win-group]:checked')].map(x=>x.value),start=window.MyPerformanceRoutine.toMin(document.getElementById('winStart').value),end=window.MyPerformanceRoutine.toMin(document.getElementById('winEnd').value);if(!groups.length||start===null||end===null||end<=start){toast('Informe horário válido e ao menos um Grupo');return}const patch={weekday:Number(document.getElementById('winDay').value),start,end,label:document.getElementById('winLabel').value.trim()||'Janela',groups,preferredGroup:document.getElementById('winPreferred').value,emergencyOnly:document.getElementById('winEmergency').checked};id?M.updateWindow(id,patch):M.addWindow(patch);closeModal();toast('Janela atualizada');render()}
  }
  function openCampaign(){modal(`<span class="eyebrow">NOVA CAMPANHA</span><h2>Adicionar Campanha</h2><p class="muted">Uma Campanha é um pacote de missões. O Grupo define em quais janelas ela pode ser planejada.</p><div class="field"><label>Nome</label><input id="campName" placeholder="Ex.: Transpetro 2026"></div><div class="field"><label>Grupo</label><select id="campGroup">${M.groups().map(g=>`<option value="${g.id}">${g.name}</option>`).join('')}</select></div><div class="form-row"><div class="field"><label>Prioridade</label><input id="campPriority" type="number" min="1" value="${M.model().campaigns.length+1}"></div><div class="field"><label>Deadline geral (opcional)</label><input id="campDeadline" type="date"></div></div><button class="btn primary" id="saveCampaign">Criar Campanha</button>`);document.getElementById('saveCampaign').onclick=()=>{const name=document.getElementById('campName').value.trim();if(!name){toast('Informe o nome da Campanha');return}M.addCampaign({name,groupId:document.getElementById('campGroup').value,priority:Number(document.getElementById('campPriority').value||1),deadline:document.getElementById('campDeadline').value});closeModal();toast('Campanha criada');render()}}
  function openCampaignMission(campaignId){const c=M.model().campaigns.find(x=>x.id===campaignId);if(!c)return;modal(`<span class="eyebrow">${esc(c.name)}</span><h2>Nova missão da Campanha</h2><div class="field"><label>Título</label><input id="cmTitle"></div><div class="field"><label>Descrição</label><textarea id="cmDesc"></textarea></div><div class="form-row"><div class="field"><label>Deadline</label><input id="cmDeadline" type="date" value="${esc(c.deadline||'')}"></div><div class="field"><label>Esforço estimado (min)</label><input id="cmDuration" type="number" min="15" step="15" value="60"></div></div><div class="field"><label>Prioridade</label><select id="cmPriority"><option value="critical">Crítica</option><option value="high" selected>Alta</option><option value="normal">Normal</option><option value="low">Baixa</option></select></div><button class="btn primary" id="saveCampaignMission">Adicionar Main Quest</button>`);document.getElementById('saveCampaignMission').onclick=()=>{const title=document.getElementById('cmTitle').value.trim();if(!title){toast('Informe um título');return}const id=`${campaignId}-mission-${Date.now().toString(36)}`,q={id,title,description:document.getElementById('cmDesc').value.trim(),domain:c.groupId,category:c.name,questType:'main',cadence:'once',startDate:today(),dueDate:document.getElementById('cmDeadline').value||c.deadline||addDays(today(),30),durationMin:Math.max(15,Number(document.getElementById('cmDuration').value||60)),priorityLevel:document.getElementById('cmPriority').value,xp:60,difficulty:3,source:`Campanha ${c.name}`,campaignId:c.id};state.customQuests.push(q);c.missionIds.push(id);M.model().missionMeta[id]={campaignId:c.id,groupId:c.groupId};saveState();closeModal();toast('Main Quest adicionada');render()}}
  function downloadCampaign(id){const pkg=M.campaignPackage(id);if(!pkg)return;const blob=new Blob([JSON.stringify(pkg,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`${pkg.campaign.name.toLowerCase().replace(/[^a-z0-9]+/g,'-')||'campanha'}.my-performance.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
  function classifyImport(pkg){modal(`<span class="eyebrow">IMPORTAR CAMPANHA</span><h2>${esc(pkg.campaign?.name||'Campanha')}</h2><p class="muted">Em qual Grupo este pacote deve consumir capacidade?</p><div class="field"><label>Grupo</label><select id="importGroup">${M.groups().map(g=>`<option value="${g.id}">${g.name}</option>`).join('')}</select></div><div class="field"><label>Prioridade</label><input id="importPriority" type="number" min="1" value="${M.model().campaigns.length+1}"></div><button class="btn primary" id="confirmImport">Importar ${pkg.missions?.length||0} missões</button>`);document.getElementById('confirmImport').onclick=()=>{try{M.importCampaign(pkg,document.getElementById('importGroup').value,Number(document.getElementById('importPriority').value||1));closeModal();toast('Campanha importada');render()}catch(e){toast(e.message||'Falha ao importar')}}}
  function editFixed(id){const q=questById(id);if(!q)return;modal(`<span class="eyebrow">COMPROMISSO ESPECIAL</span><h2>${esc(q.title)}</h2><p class="muted">Este é um horário realmente fixo. O motor nunca o desloca.</p><div class="form-row"><div class="field"><label>Início</label><input id="fixedStart" type="time" value="${esc(q.timeStart||'')}"></div><div class="field"><label>Fim</label><input id="fixedEnd" type="time" value="${esc(q.timeEnd||'')}"></div></div><div class="form-row"><div class="field"><label>Buffer antes (min)</label><input id="fixedBefore" type="number" min="0" value="${Number(q.bufferBeforeMin||0)}"></div><div class="field"><label>Buffer depois (min)</label><input id="fixedAfter" type="number" min="0" value="${Number(q.bufferAfterMin||0)}"></div></div><button class="btn primary" id="saveFixed">Salvar missão</button>`);document.getElementById('saveFixed').onclick=()=>{state.overrides[id]=Object.assign({},state.overrides[id]||{},{timeStart:document.getElementById('fixedStart').value,timeEnd:document.getElementById('fixedEnd').value,bufferBeforeMin:Math.max(0,Number(document.getElementById('fixedBefore').value||0)),bufferAfterMin:Math.max(0,Number(document.getElementById('fixedAfter').value||0)),fixedTime:true,immovable:true,specialCommitment:true});saveState();closeModal();toast('Compromisso atualizado');render()}}

  function bindConfigV3(){
    document.getElementById('addWindow').onclick=()=>openWindow();document.querySelectorAll('[data-window-edit]').forEach(b=>b.onclick=()=>openWindow(b.dataset.windowEdit));document.querySelectorAll('[data-window-delete]').forEach(b=>b.onclick=()=>{if(confirm('Excluir esta janela de capacidade? As missões serão redistribuídas nas demais janelas.')){M.removeWindow(b.dataset.windowDelete);render()}});
    document.getElementById('addCampaign').onclick=openCampaign;document.querySelectorAll('[data-camp-up]').forEach(b=>b.onclick=()=>{M.moveCampaign(b.dataset.campUp,-1);render()});document.querySelectorAll('[data-camp-down]').forEach(b=>b.onclick=()=>{M.moveCampaign(b.dataset.campDown,1);render()});document.querySelectorAll('[data-camp-export]').forEach(b=>b.onclick=()=>downloadCampaign(b.dataset.campExport));document.querySelectorAll('[data-camp-add-mission]').forEach(b=>b.onclick=()=>openCampaignMission(b.dataset.campAddMission));document.querySelectorAll('[data-camp-delete]').forEach(b=>b.onclick=()=>{const c=M.model().campaigns.find(x=>x.id===b.dataset.campDelete);if(c&&confirm(`Excluir a Campanha “${c.name}” e suas ${c.missionIds.length} missões? Esta ação remove o pacote do planejamento.`)){M.deleteCampaign(c.id);toast('Campanha excluída');render()}});
    document.querySelectorAll('[data-fixed-edit]').forEach(b=>b.onclick=()=>editFixed(b.dataset.fixedEdit));
    document.getElementById('importCampaign').onclick=()=>document.getElementById('campaignFile').click();document.getElementById('campaignFile').onchange=async e=>{const f=e.target.files?.[0];if(!f)return;try{classifyImport(JSON.parse(await f.text()))}catch{toast('Arquivo de Campanha inválido')}};
    document.getElementById('saveEngine').onclick=()=>{const e=M.model().engine;e.horizonDays=Math.max(14,Math.min(180,Number(document.getElementById('engineHorizon').value||90)));e.safetyDays=Math.max(0,Math.min(14,Number(document.getElementById('engineSafety').value||2)));e.maxSessionMin=Math.max(30,Math.min(240,Number(document.getElementById('engineMaxSession').value||120)));saveState();toast('Políticas do motor atualizadas');render()}
  }

  function renderAgendaV3(){
    const start=state.calendarWeekStart||weekStart(state.plannerDate||today()),dates=Array.from({length:7},(_,i)=>addDays(start,i)),view=document.getElementById('view');
    view.innerHTML=`<div class="section-title"><div><span class="eyebrow">CALENDÁRIO SEMANAL</span><h2>${fmt(start)} – ${fmt(addDays(start,6))}</h2><p class="muted">O calendário mostra o resultado do mesmo Planner Engine usado na tela Hoje.</p></div><div class="day-nav"><button class="btn small" id="weekPrev">← semana</button><button class="btn small" id="weekNow">Atual</button><button class="btn small" id="weekNext">semana →</button></div></div><div class="week-calendar">${dates.map(date=>{const p=E.planDay(date),main=p.slots.filter(x=>x.mainQuest).length,fixed=p.slots.filter(x=>x.fixed&&!x.buffer).length;return`<button class="week-day ${date===today()?'today':''}" data-open-day="${date}"><span>${esc(short(dow(date)))}</span><b>${fmt(date,{day:'2-digit'})}</b><small>${p.slots.length} blocos · ${main} Main · ${fixed} fixos</small>${p.risks?.length?'<i>⚠ prazo</i>':''}</button>`}).join('')}</div><div class="agenda-days">${dates.map(date=>{const p=E.planDay(date);return`<div class="card agenda-day"><div class="section-title"><div><span class="eyebrow">${esc(DAYS[dow(date)])}</span><h3>${fmt(date)}</h3></div></div>${p.slots.filter(x=>!x.buffer).slice(0,8).map(x=>`<div class="agenda-line"><b>${time(x.start)}</b><span>${x.fixed?'🔒 ':x.mainQuest?'◆ ':''}${esc(x.q.title)}</span></div>`).join('')||'<div class="empty">Sem missões.</div>'}</div>`}).join('')}</div>`;
    document.getElementById('weekPrev').onclick=()=>{state.calendarWeekStart=addDays(start,-7);saveState();render()};document.getElementById('weekNow').onclick=()=>{state.calendarWeekStart=weekStart(today());saveState();render()};document.getElementById('weekNext').onclick=()=>{state.calendarWeekStart=addDays(start,7);saveState();render()};document.querySelectorAll('[data-open-day]').forEach(b=>b.onclick=()=>{state.plannerDate=b.dataset.openDay;state.view='today';saveState();render()})
  }

  function renderDashboardV3(){
    const p=E.planDay(today()),now=E.missionNow(),c=M.model(),s=completions(),r=rank();
    document.getElementById('view').innerHTML=`<div class="grid2"><div class="card hero"><span class="pill green">MY PERFORMANCE 2.0</span><h2>${esc(state.name)}, seu calendário virou o tabuleiro.</h2><p class="muted">Main Quests são distribuídas nas janelas certas. Compromissos fixos permanecem imóveis. Side Quests cedem apenas quando o prazo realmente exige.</p><div class="hero-kpis"><div class="kpi"><span>XP total</span><strong>${s.xp.toLocaleString('pt-BR')}</strong></div><div class="kpi"><span>Nível</span><strong>${r.index}</strong></div><div class="kpi"><span>Missões hoje</span><strong>${p.slots.filter(x=>!x.buffer).length}</strong></div><div class="kpi"><span>Campanhas</span><strong>${c.campaigns.length}</strong></div></div></div><div class="card"><span class="eyebrow">AGORA</span><h2>${now.current?esc(now.current.q.title):'Nenhuma missão em andamento'}</h2><p class="muted">${now.current?`${time(now.current.start)}–${time(now.current.end)} · ${now.current.campaignName||now.current.q.domain}`:now.next?`Próxima: ${time(now.next.start)} · ${esc(now.next.q.title)}`:'Agenda livre neste momento.'}</p><button class="btn primary" data-go="today">Abrir calendário de hoje</button></div></div><div class="section-title"><div><h2>Campanhas ativas</h2><p class="muted">Prioridade influencia o motor, mas não substitui deadline e viabilidade.</p></div></div><div class="campaign-list">${c.campaigns.map(campaignCard).join('')}</div><div class="section-title"><div><h2>Próximas missões</h2></div></div><div class="card">${p.slots.filter(x=>!x.buffer).slice(0,8).map(x=>`<div class="statline"><span>${time(x.start)} · ${x.fixed?'🔒 ':x.mainQuest?'◆ ':''}${esc(x.q.title)}</span><b>${esc(x.campaignName||x.q.domain)}</b></div>`).join('')||'<div class="empty">Agenda livre.</div>'}</div>`;document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));document.querySelectorAll('[data-camp-export],[data-camp-delete],[data-camp-up],[data-camp-down],[data-camp-add-mission]').forEach(b=>b.style.display='none')
  }

  function renderQuestsV3(){if(BASE.quests)BASE.quests();document.querySelectorAll('#fDomain option').forEach(o=>{if(o.value==='Carreira'||o.textContent==='Carreira')o.remove()});document.querySelectorAll('.tag.Carreira').forEach(x=>{x.textContent='Pessoal';x.classList.remove('Carreira');x.classList.add('Pessoal')})}

  const legacyTimeline=BASE.timeline;
  renderToday=renderTodayV3;renderConfig=renderConfigV3;renderAgenda=renderAgendaV3;renderDashboard=renderDashboardV3;renderQuests=renderQuestsV3;
  render=function(){
    try{renderHud()}catch{};
    const fn={dashboard:renderDashboardV3,today:renderTodayV3,quests:renderQuestsV3,agenda:renderAgendaV3,timeline:legacyTimeline||renderAgendaV3,player:BASE.player,rewards:BASE.rewards,config:renderConfigV3}[state.view]||renderDashboardV3;
    if(typeof fn==='function')fn();else renderDashboardV3();document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===state.view));window.dispatchEvent(new CustomEvent('my-performance-view-rendered',{detail:{view:state.view,engine:'calendar-v3'}}))
  };

  // Remove the legacy domain from any quest modal that still comes from the original editor.
  const mo=new MutationObserver(()=>{document.querySelectorAll('#modal option').forEach(o=>{if((o.value||o.textContent)==='Carreira')o.remove()})});mo.observe(document.getElementById('modal'),{childList:true,subtree:true});
  window.addEventListener('my-performance-cloud-loaded',()=>{M.model();setTimeout(render,0)});
  window.MyPerformanceCalendarUI={BUILD,renderToday:renderTodayV3,renderConfig:renderConfigV3,renderAgenda:renderAgendaV3};
  setTimeout(render,0);
})();