"use strict";
/* Neon local-first sync with revision/conflict protection for multi-device use. */
const NEON_AUTH_URL='https://ep-fancy-wave-a6thlzk9.neonauth.us-west-2.aws.neon.tech/neondb/auth';
const NEON_DATA_API_URL='https://ep-fancy-wave-a6thlzk9.apirest.us-west-2.aws.neon.tech/neondb/rest/v1';
const NEON_SDK_URL='https://esm.sh/@neondatabase/neon-js@0.6.3-beta?bundle';
const N_EMAIL='my_performance_neon_email',N_ENABLED='my_performance_neon_enabled',N_LAST_SYNC='my_performance_neon_last_sync',N_LOCAL_UPDATED='my_performance_local_updated',N_STATE_KEY='my_performance_v1',N_DEVICE='my_performance_device_id',N_REMOTE_REV='my_performance_remote_revision';
localStorage.removeItem('my_performance_neon_sync_key');localStorage.removeItem('my_performance_neon_endpoint');localStorage.removeItem('my_performance_neon_profile');
function uid(){return(globalThis.crypto?.randomUUID?.()||`dev-${Date.now().toString(36)}-${Math.random().toString(36).slice(2)}`)}
const DEVICE_ID=localStorage.getItem(N_DEVICE)||uid();localStorage.setItem(N_DEVICE,DEVICE_ID);
const neonSync={email:localStorage.getItem(N_EMAIL)||'',enabled:localStorage.getItem(N_ENABLED)==='1',syncing:false,applyingRemote:false,timer:null,lastSnapshot:localStorage.getItem(N_STATE_KEY)||'',lastRemoteRevision:Number(localStorage.getItem(N_REMOTE_REV)||0),clientPromise:null,conflict:null};
function status(msg,kind=''){const e=document.getElementById('cloudStatus');if(!e)return;e.textContent=msg;e.style.color=kind==='ok'?'var(--green)':kind==='error'?'var(--red)':'var(--muted2)'}
async function getClient(){if(!neonSync.clientPromise)neonSync.clientPromise=import(NEON_SDK_URL).then(({createClient})=>createClient({auth:{url:NEON_AUTH_URL},dataApi:{url:NEON_DATA_API_URL}}));return neonSync.clientPromise}
function unwrapAuth(result){if(result?.error)throw new Error(result.error.message||result.error.statusText||'Falha de autenticação.');return result?.data??result}
function unpack(x){return Array.isArray(x)?x[0]:x}
function markLocal(){localStorage.setItem(N_LOCAL_UPDATED,new Date().toISOString())}
function localObj(){try{return JSON.parse(localStorage.getItem(N_STATE_KEY)||'{}')}catch{return{}}}
function revision(o){return Math.max(0,Number(o?._sync?.revision||0))}
function setRemoteRevision(n){neonSync.lastRemoteRevision=Math.max(0,Number(n||0));localStorage.setItem(N_REMOTE_REV,String(neonSync.lastRemoteRevision))}
function meaningfulLocal(o){return revision(o)>0||Object.keys(o?.completed||{}).length>0||(o?.customQuests||[]).length>0||Object.keys(o?.schedulerV2?.blockCompletions||{}).length>0}
async function session(){try{const client=await getClient(),raw=await client.auth.getSession(),data=unwrapAuth(raw);return data?.session||data?.user?data:null}catch{return null}}
async function rpc(name,args={}){const client=await getClient(),result=await client.rpc(name,args);if(result?.error)throw new Error(result.error.message||`Falha em ${name}`);return result?.data}
function unionById(a=[],b=[]){const m=new Map();for(const x of a.concat(b)){if(x&&typeof x==='object'&&x.id)m.set(x.id,Object.assign({},m.get(x.id)||{},x));else m.set(JSON.stringify(x),x)}return[...m.values()]}
function mergePlain(remote,local){if(Array.isArray(remote)||Array.isArray(local))return Array.isArray(local)?local:Array.isArray(remote)?remote:[];if(!remote||typeof remote!=='object')return local??remote;if(!local||typeof local!=='object')return remote;const out=Object.assign({},remote);for(const[k,v]of Object.entries(local)){if(v&&typeof v==='object'&&!Array.isArray(v)&&remote[k]&&typeof remote[k]==='object'&&!Array.isArray(remote[k]))out[k]=mergePlain(remote[k],v);else out[k]=v}return out}
function mergeStates(remote,local){const out=mergePlain(remote,local);out.activityDates=[...new Set([...(remote.activityDates||[]),...(local.activityDates||[])])].sort();out.customQuests=unionById(remote.customQuests,local.customQuests);out.rewardLog=unionById(remote.rewardLog,local.rewardLog);out.completed=Object.assign({},remote.completed||{},local.completed||{});out.xpLedger=Object.assign({},remote.xpLedger||{},local.xpLedger||{});out.bonusLedger=Object.assign({},remote.bonusLedger||{},local.bonusLedger||{});out.schedulerV2=mergePlain(remote.schedulerV2||{},local.schedulerV2||{});return out}
function conflictCard(){if(!neonSync.conflict)return'';const c=neonSync.conflict;return`<div class="card sync-conflict-card" id="cloudConflict"><span class="eyebrow">CONFLITO ENTRE DISPOSITIVOS</span><h2>Há mudanças diferentes no PC/celular</h2><p class="muted">A nuvem está na revisão ${c.remoteRevision}; este dispositivo partiu da revisão ${c.baseRevision}. Nada foi sobrescrito automaticamente.</p><div class="sync-conflict-actions"><button class="btn" id="cloudUseRemote">Usar nuvem</button><button class="btn" id="cloudMerge">Mesclar alterações</button><button class="btn danger" id="cloudUseLocal">Usar este dispositivo</button></div></div>`}
function renderConflictUI(){document.getElementById('cloudConflict')?.remove();if(!neonSync.conflict)return;const host=document.getElementById('cloudStatus')?.closest('.card')||document.getElementById('view');host?.insertAdjacentHTML('beforeend',conflictCard());document.getElementById('cloudUseRemote')?.addEventListener('click',resolveRemote);document.getElementById('cloudUseLocal')?.addEventListener('click',resolveLocal);document.getElementById('cloudMerge')?.addEventListener('click',resolveMerge)}
function setConflict(remoteObj,remoteUpdated){const local=localObj();neonSync.conflict={remote:remoteObj,local,remoteUpdated,remoteRevision:revision(remoteObj),baseRevision:neonSync.lastRemoteRevision};status('Conflito detectado — escolha como resolver antes de sincronizar.','error');renderConflictUI();window.dispatchEvent(new CustomEvent('my-performance-sync-conflict',{detail:{remoteRevision:revision(remoteObj),baseRevision:neonSync.lastRemoteRevision}}))}
function applyRemoteObject(remoteObj,stamp){const remote=JSON.stringify(remoteObj);neonSync.applyingRemote=true;localStorage.setItem(N_STATE_KEY,remote);neonSync.lastSnapshot=remote;localStorage.setItem(N_LAST_SYNC,stamp||new Date().toISOString());localStorage.setItem(N_LOCAL_UPDATED,stamp||new Date().toISOString());setRemoteRevision(revision(remoteObj));window.dispatchEvent(new CustomEvent('my-performance-cloud-loaded',{detail:remoteObj}));setTimeout(()=>neonSync.applyingRemote=false,350)}
async function remoteSnapshot(){return unpack(await rpc('my_performance_pull'))}
async function push({force=false,bypassConflict=false}={}){if(!neonSync.enabled||neonSync.syncing)return false;const auth=await session();if(!auth){status('Entre na sua conta Neon para sincronizar.','error');return false}let obj=localObj(),raw=JSON.stringify(obj);if(!raw)return false;if(!force&&raw===neonSync.lastSnapshot)return false;neonSync.syncing=true;status('Verificando revisão da nuvem…');try{const remote=await remoteSnapshot(),remoteObj=remote?.state||{},remoteRev=remote?.found?revision(remoteObj):0;if(remote?.found&&!bypassConflict&&remoteRev>neonSync.lastRemoteRevision&&JSON.stringify(remoteObj)!==raw){setConflict(remoteObj,remote.updated_at||remote.updatedAt||'');return false}const nextRev=Math.max(revision(obj),remoteRev,neonSync.lastRemoteRevision)+1;obj._sync={revision:nextRev,deviceId:DEVICE_ID,updatedAt:new Date().toISOString(),baseRevision:remoteRev};raw=JSON.stringify(obj);localStorage.setItem(N_STATE_KEY,raw);const out=unpack(await rpc('my_performance_push',{p_state:obj})),stamp=out?.updated_at||out?.updatedAt||new Date().toISOString();neonSync.lastSnapshot=raw;setRemoteRevision(nextRev);localStorage.setItem(N_LAST_SYNC,stamp);localStorage.setItem(N_LOCAL_UPDATED,stamp);neonSync.conflict=null;renderConflictUI();status(`Neon sincronizado · revisão ${nextRev} · ${new Date(stamp).toLocaleString('pt-BR')}`,'ok');return true}catch(e){status(`Cloud indisponível · ${e.message}`,'error');return false}finally{neonSync.syncing=false}}
async function pull({force=false}={}){if(!neonSync.enabled||neonSync.syncing)return false;const auth=await session();if(!auth){status('Entre na sua conta Neon para sincronizar.','error');return false}neonSync.syncing=true;status('Comparando PC/celular com a nuvem…');try{const out=await remoteSnapshot(),local=localObj(),localRaw=JSON.stringify(local);if(!out?.found){neonSync.syncing=false;status('Primeiro acesso — criando seu save na nuvem…');return push({force:true,bypassConflict:true})}const remoteObj=out.state||{},remoteRaw=JSON.stringify(remoteObj),remoteUpdated=out.updated_at||out.updatedAt||'',remoteRev=revision(remoteObj),localRev=revision(local);if(Object.keys(remoteObj).length===0&&meaningfulLocal(local)){neonSync.syncing=false;return push({force:true,bypassConflict:true})}if(!force&&remoteRev>neonSync.lastRemoteRevision&&meaningfulLocal(local)&&localRaw!==neonSync.lastSnapshot&&localRaw!==remoteRaw){setConflict(remoteObj,remoteUpdated);return false}if(localRev===0&&remoteRev>0||force||remoteRaw!==localRaw){applyRemoteObject(remoteObj,remoteUpdated||new Date().toISOString())}setRemoteRevision(remoteRev);neonSync.conflict=null;renderConflictUI();status(`PC/celular sincronizados · revisão ${remoteRev} · ${new Date(remoteUpdated||Date.now()).toLocaleString('pt-BR')}`,'ok');return true}catch(e){status(`Cloud indisponível · ${e.message}`,'error');return false}finally{neonSync.syncing=false}}
async function resolveRemote(){if(!neonSync.conflict)return;const c=neonSync.conflict;applyRemoteObject(c.remote,c.remoteUpdated||new Date().toISOString());neonSync.conflict=null;renderConflictUI();status('Versão da nuvem aplicada sem apagar o backup remoto.','ok');render()}
async function resolveLocal(){if(!neonSync.conflict)return;setRemoteRevision(neonSync.conflict.remoteRevision);neonSync.conflict=null;renderConflictUI();await push({force:true,bypassConflict:true});window.dispatchEvent(new CustomEvent('my-performance-cloud-loaded',{detail:localObj()}));render()}
async function resolveMerge(){if(!neonSync.conflict)return;const merged=mergeStates(neonSync.conflict.remote,neonSync.conflict.local);localStorage.setItem(N_STATE_KEY,JSON.stringify(merged));setRemoteRevision(neonSync.conflict.remoteRevision);neonSync.conflict=null;renderConflictUI();window.dispatchEvent(new CustomEvent('my-performance-cloud-loaded',{detail:merged}));await push({force:true,bypassConflict:true});render();status('Alterações mescladas e sincronizadas.','ok')}
function schedulePush(){if(!neonSync.enabled||neonSync.applyingRemote||neonSync.conflict)return;clearTimeout(neonSync.timer);neonSync.timer=setTimeout(()=>push(),900)}
async function signIn(email,password){if(!email||!password){status('Informe e-mail e senha.','error');return false}status('Entrando no Neon Auth…');try{const client=await getClient();unwrapAuth(await client.auth.signIn.email({email,password}));neonSync.email=email;neonSync.enabled=true;localStorage.setItem(N_EMAIL,email);localStorage.setItem(N_ENABLED,'1');status('Login realizado. Sincronizando…','ok');await pull();bindUI();return true}catch(e){status(`Login falhou · ${e.message}`,'error');return false}}
async function signUp(email,password){if(!email||!password){status('Informe e-mail e senha.','error');return false}if(password.length<8){status('Use uma senha com pelo menos 8 caracteres.','error');return false}status('Criando sua conta Neon Auth…');try{const client=await getClient();unwrapAuth(await client.auth.signUp.email({email,password,name:'Vitor'}));neonSync.email=email;neonSync.enabled=true;localStorage.setItem(N_EMAIL,email);localStorage.setItem(N_ENABLED,'1');const logged=await session();if(!logged)unwrapAuth(await client.auth.signIn.email({email,password}));status('Conta criada. Criando seu save na nuvem…','ok');await pull();bindUI();return true}catch(e){status(`Cadastro falhou · ${e.message}`,'error');return false}}
async function signOut(){try{const client=await getClient();await client.auth.signOut()}catch{}neonSync.enabled=false;localStorage.setItem(N_ENABLED,'0');status('Sessão encerrada. Seus dados locais continuam neste dispositivo.');bindUI()}
async function bindUI(){const ep=document.getElementById('cloudEndpoint'),email=document.getElementById('cloudProfile'),pw=document.getElementById('cloudKey'),en=document.getElementById('cloudEnabled');if(!ep||!email||!pw||!en)return;ep.value=NEON_DATA_API_URL;ep.readOnly=true;const epLabel=ep.closest('.field')?.querySelector('label');if(epLabel)epLabel.textContent='Neon Data API (configurada)';const emailLabel=email.closest('.field')?.querySelector('label');if(emailLabel)emailLabel.textContent='E-mail da conta';const pwLabel=pw.closest('.field')?.querySelector('label');if(pwLabel)pwLabel.textContent='Senha Neon Auth';email.type='email';email.placeholder='seu@email.com';email.value=neonSync.email;pw.value='';pw.placeholder='não é salva neste navegador';en.checked=neonSync.enabled;const login=document.getElementById('cloudSave');login.textContent='Entrar e sincronizar';const actions=login.parentElement;let signup=document.getElementById('cloudSignup');if(!signup){signup=document.createElement('button');signup.id='cloudSignup';signup.className='btn';signup.textContent='Criar conta';actions.insertBefore(signup,document.getElementById('cloudPull'))}let logout=document.getElementById('cloudLogout');if(!logout){logout=document.createElement('button');logout.id='cloudLogout';logout.className='btn';logout.textContent='Sair';actions.appendChild(logout)}const auth=await session();if(auth){const user=auth.user||auth.session?.user,currentEmail=user?.email||neonSync.email;if(currentEmail){neonSync.email=currentEmail;email.value=currentEmail;localStorage.setItem(N_EMAIL,currentEmail)}status(`Conectado${currentEmail?' como '+currentEmail:''}. Cloud Sync ${neonSync.enabled?'ativa':'pausada'} · revisão ${neonSync.lastRemoteRevision}.`,'ok')}else status('Sem login. Crie uma conta ou entre para ativar o save em nuvem.');login.onclick=()=>{neonSync.enabled=true;en.checked=true;signIn(email.value.trim(),pw.value)};signup.onclick=()=>{neonSync.enabled=true;en.checked=true;signUp(email.value.trim(),pw.value)};logout.onclick=signOut;en.onchange=()=>{neonSync.enabled=en.checked;localStorage.setItem(N_ENABLED,en.checked?'1':'0');status(en.checked?'Cloud Sync ativada. Faça login se necessário.':'Cloud Sync pausada.');if(en.checked)pull()};document.getElementById('cloudPull').onclick=()=>pull({force:true});document.getElementById('cloudPush').onclick=()=>{markLocal();push({force:true})};renderConflictUI()}
window.addEventListener('my-performance-state-saved',()=>{if(!neonSync.applyingRemote){markLocal();schedulePush()}});window.addEventListener('my-performance-view-rendered',e=>{if(e.detail?.view==='config')bindUI()});
window.MyPerformanceCloud={bindUI,pull,push,signIn,signUp,signOut,resolveRemote,resolveLocal,resolveMerge,status:()=>({email:neonSync.email,enabled:neonSync.enabled,lastSync:localStorage.getItem(N_LAST_SYNC),revision:neonSync.lastRemoteRevision,deviceId:DEVICE_ID,conflict:!!neonSync.conflict})};if(neonSync.enabled)session().then(s=>{if(s)pull()});
