"use strict";
const N_ENDPOINT='my_performance_neon_endpoint';
const N_PROFILE='my_performance_neon_profile';
const N_KEY='my_performance_neon_sync_key';
const N_ENABLED='my_performance_neon_enabled';
const N_LAST_SYNC='my_performance_neon_last_sync';
const N_LOCAL_UPDATED='my_performance_local_updated';
const N_STATE_KEY='my_performance_v1';
const neonSync={endpoint:localStorage.getItem(N_ENDPOINT)||'',profile:localStorage.getItem(N_PROFILE)||'vitor',key:localStorage.getItem(N_KEY)||'',enabled:localStorage.getItem(N_ENABLED)==='1',syncing:false,applyingRemote:false,timer:null,lastSnapshot:localStorage.getItem(N_STATE_KEY)||''};
function status(msg,kind=''){const e=document.getElementById('cloudStatus');if(!e)return;e.textContent=msg;e.style.color=kind==='ok'?'var(--green)':kind==='error'?'var(--red)':'var(--muted2)'}
function base(){return (neonSync.endpoint||'').trim().replace(/\/+$/,'')}
async function rpc(name,payload){if(!base())throw new Error('Informe a URL da Neon Data API.');const r=await fetch(`${base()}/rpc/${name}`,{method:'POST',headers:{'content-type':'application/json','accept':'application/json'},body:JSON.stringify(payload),cache:'no-store'});const text=await r.text();let data;try{data=text?JSON.parse(text):null}catch{data=text}if(!r.ok)throw new Error((data&&data.message)||`HTTP ${r.status}`);return data}
function unpack(x){return Array.isArray(x)?x[0]:x}
function markLocal(){localStorage.setItem(N_LOCAL_UPDATED,new Date().toISOString())}
async function push({force=false}={}){if(!neonSync.enabled||!neonSync.key||!base()||neonSync.syncing)return false;const raw=localStorage.getItem(N_STATE_KEY)||'';if(!raw)return false;if(!force&&raw===neonSync.lastSnapshot)return false;neonSync.syncing=true;status('Salvando no Neon…');try{const out=unpack(await rpc('my_performance_push',{p_profile:neonSync.profile,p_key:neonSync.key,p_state:JSON.parse(raw)}));const stamp=out?.updated_at||out?.updatedAt||new Date().toISOString();neonSync.lastSnapshot=raw;localStorage.setItem(N_LAST_SYNC,stamp);localStorage.setItem(N_LOCAL_UPDATED,stamp);status(`Neon sincronizado · ${new Date(stamp).toLocaleString('pt-BR')}`,'ok');return true}catch(e){status(`Cloud indisponível · ${e.message}`,'error');return false}finally{neonSync.syncing=false}}
async function pull({force=false}={}){if(!neonSync.enabled||!neonSync.key||!base()||neonSync.syncing)return false;neonSync.syncing=true;status('Baixando do Neon…');try{const out=unpack(await rpc('my_performance_pull',{p_profile:neonSync.profile,p_key:neonSync.key}));if(!out?.found){status('Perfil não encontrado no Neon. Execute neon-setup.sql primeiro.','error');return false}const remote=JSON.stringify(out.state||{}),local=localStorage.getItem(N_STATE_KEY)||'{}',remoteUpdated=out.updated_at||out.updatedAt||'',localUpdated=localStorage.getItem(N_LOCAL_UPDATED)||'';if(!force&&localUpdated&&remoteUpdated&&localUpdated>remoteUpdated&&local!==remote){neonSync.syncing=false;return push({force:true})}if(force||remote!==local){neonSync.applyingRemote=true;localStorage.setItem(N_STATE_KEY,remote);neonSync.lastSnapshot=remote;localStorage.setItem(N_LAST_SYNC,remoteUpdated||new Date().toISOString());localStorage.setItem(N_LOCAL_UPDATED,remoteUpdated||new Date().toISOString());window.dispatchEvent(new CustomEvent('my-performance-cloud-loaded',{detail:out.state}));setTimeout(()=>neonSync.applyingRemote=false,250)}status(`PC/celular sincronizados · ${new Date(remoteUpdated||Date.now()).toLocaleString('pt-BR')}`,'ok');return true}catch(e){status(`Cloud indisponível · ${e.message}`,'error');return false}finally{neonSync.syncing=false}}
function schedulePush(){if(!neonSync.enabled||!neonSync.key||!base()||neonSync.applyingRemote)return;clearTimeout(neonSync.timer);neonSync.timer=setTimeout(()=>push(),900)}
function bindUI(){const ep=document.getElementById('cloudEndpoint'),pr=document.getElementById('cloudProfile'),key=document.getElementById('cloudKey'),en=document.getElementById('cloudEnabled');if(!ep||!pr||!key||!en)return;ep.value=neonSync.endpoint;pr.value=neonSync.profile;key.value=neonSync.key;en.checked=neonSync.enabled;status(neonSync.enabled?'Neon Cloud Sync pronto.':'Sincronização desativada.');document.getElementById('cloudSave').onclick=async()=>{neonSync.endpoint=ep.value.trim();neonSync.profile=(pr.value||'vitor').trim();neonSync.key=key.value;neonSync.enabled=en.checked;localStorage.setItem(N_ENDPOINT,neonSync.endpoint);localStorage.setItem(N_PROFILE,neonSync.profile);localStorage.setItem(N_KEY,neonSync.key);localStorage.setItem(N_ENABLED,neonSync.enabled?'1':'0');if(!neonSync.enabled){status('Sincronização desativada.');return}if(!neonSync.endpoint||!neonSync.key){status('Informe URL da Data API e chave.','error');return}const ok=await pull();if(!ok)status('Confira a Data API, o SQL de setup e a chave.','error')};document.getElementById('cloudPull').onclick=()=>pull({force:true});document.getElementById('cloudPush').onclick=()=>{markLocal();push({force:true})}}
window.addEventListener('my-performance-state-saved',()=>{if(!neonSync.applyingRemote){markLocal();schedulePush()}});window.addEventListener('my-performance-view-rendered',e=>{if(e.detail?.view==='config')bindUI()});window.MyPerformanceCloud={bindUI,pull,push,status:()=>({endpoint:neonSync.endpoint,profile:neonSync.profile,enabled:neonSync.enabled,lastSync:localStorage.getItem(N_LAST_SYNC)})};if(neonSync.enabled&&neonSync.key&&base())pull();
