"use strict";
/* Smart Planner layer — daily programmatic agenda, goal breakdowns and Gantt. */
(() => {
  const BASE_RENDER = render;
  const BASE_BIND_QUEST_CARDS = bindQuestCards;
  const BASE_TOGGLE_QUEST = toggleQuest;
  const DEFAULT_DURATION = 45;
  const BUFFER_MIN = 10;
  const MAX_AWAKE_MIN = 16 * 60;

  const BLUEPRINTS = {
    'gsa-c1': {durationMin:120, scope:'global', subtasks:[
      {id:'qualified',title:'Conversas qualificadas no RIW',kind:'metric',target:30,unit:'contatos'},
      {id:'industries',title:'Indústrias do RJ candidatas',kind:'metric',target:5,unit:'indústrias'}
    ]},
    'gsa-c10': {durationMin:120, scope:'global', subtasks:[
      {id:'sis',title:'Cadastro no SisFAPERJ concluído',kind:'check'},
      {id:'lattes',title:'Lattes do proponente e equipe pronto',kind:'check'},
      {id:'letter',title:'Carta de Interesse assinada',kind:'check'},
      {id:'proformas',title:'Proformas de todos os fornecedores',kind:'check'},
      {id:'trl',title:'TRL 6 demonstrado e gravado',kind:'check'},
      {id:'video',title:'Vídeo de 4 minutos publicado',kind:'check'},
      {id:'submit',title:'Proposta submetida no SisFAPERJ',kind:'check'}
    ]},
    'gsa-s11': {durationMin:60, scope:'global', subtasks:[
      {id:'partners',title:'Parceiros ativos',kind:'metric',target:12,unit:'parceiros'},
      {id:'architects',title:'Arquitetos ativos',kind:'metric',target:4,unit:'arquitetos'}
    ]},
    'gsa-s12': {durationMin:60, scope:'global', subtasks:[
      {id:'aug',title:'Faturamento de agosto',kind:'metric',target:10000,unit:'R$'},
      {id:'sep',title:'Faturamento de setembro',kind:'metric',target:11400,unit:'R$'},
      {id:'oct',title:'Faturamento de outubro',kind:'metric',target:12500,unit:'R$'},
      {id:'nov',title:'Faturamento de novembro',kind:'metric',target:13500,unit:'R$'},
      {id:'dec',title:'Faturamento de dezembro',kind:'metric',target:14000,unit:'R$'}
    ]},
    'gsa-p4': {durationMin:60, scope:'global', subtasks:[{id:'techs',title:'Técnicos cadastrados',kind:'metric',target:10,unit:'técnicos'}]},
    'gsa-p10': {durationMin:60, scope:'global', subtasks:[{id:'users',title:'Usuários reais atendidos no Lakshimi',kind:'metric',target:10,unit:'usuários'}]},
    'gsa-p11': {durationMin:60, scope:'global', subtasks:[{id:'works',title:'Obras registradas ponta a ponta',kind:'metric',target:20,unit:'obras'}]},
    'gsa-p12': {durationMin:45, scope:'global', subtasks:[{id:'eva',title:'Assinaturas EVA ativas',kind:'metric',target:11,unit:'assinaturas'}]},
    'gsa-r-diag': {durationMin:60, scope:'global', subtasks:[{id:'diagnostics',title:'Diagnósticos realizados no período',kind:'metric',target:25,unit:'diagnósticos'}]},
    'gsa-r-post': {durationMin:45, scope:'monthly', subtasks:[{id:'posts',title:'Conteúdos publicados no mês',kind:'metric',target:8,unit:'posts'},{id:'bench',title:'Vídeo da bancada no mês',kind:'metric',target:1,unit:'vídeo'}]},
    'study-w-hours': {durationMin:45, subtasks:[{id:'hours',title:'Horas líquidas de estudo',kind:'metric',target:12,unit:'h'}]},
    'study-w-q250': {durationMin:45, subtasks:[{id:'questions',title:'Questões corrigidas',kind:'metric',target:250,unit:'questões'}]},
    'study-w-bosses': {durationMin:45, subtasks:[{id:'bosses',title:'Bosses técnicos realizados',kind:'metric',target:2,unit:'bosses'}]},
    'study-w-errors': {durationMin:45, subtasks:[{id:'errors',title:'Erros revisados',kind:'metric',target:20,unit:'erros'}]},
    'study-aug-diag': {durationMin:75, subtasks:[
      {id:'mechanical',title:'Diagnóstico Mecânica',kind:'check'},
      {id:'supply',title:'Diagnóstico Comércio / Suprimentos',kind:'check'},
      {id:'maritime',title:'Diagnóstico Transporte Marítimo',kind:'check'}
    ]},
    'study-aug-volume': {durationMin:60, subtasks:[{id:'q',title:'Questões resolvidas e corrigidas',kind:'metric',target:600,unit:'questões'}]},
    'study-sep-volume': {durationMin:60, subtasks:[{id:'q',title:'Questões resolvidas e corrigidas',kind:'metric',target:1000,unit:'questões'}]},
    'study-oct-volume': {durationMin:60, subtasks:[{id:'q',title:'Questões resolvidas e corrigidas',kind:'metric',target:1200,unit:'questões'}]},
    'study-sep-boss': {durationMin:60, subtasks:[{id:'bosses',title:'Bosses realizados',kind:'metric',target:4,unit:'bosses'}]},
    'study-oct-bosses': {durationMin:60, subtasks:[{id:'bosses',title:'Bosses realizados',kind:'metric',target:8,unit:'bosses'}]},
    'study-oct-full': {durationMin:90, subtasks:[{id:'sim',title:'Simulados completos de 70 questões',kind:'metric',target:3,unit:'simulados'}]},
    'study-nov-trinca': {durationMin:90, subtasks:[{id:'scores',title:'Simulados consecutivos com 42+',kind:'metric',target:3,unit:'simulados'}]},
    'study-aug-score': {durationMin:90, subtasks:[{id:'score',title:'Melhor resultado nas específicas',kind:'metric',target:30,unit:'pontos'}]},
    'study-sep-score': {durationMin:90, subtasks:[{id:'score',title:'Melhor resultado nas específicas',kind:'metric',target:35,unit:'pontos'}]},
    'study-oct-score': {durationMin:90, subtasks:[{id:'score',title:'Melhor resultado nas específicas',kind:'metric',target:39,unit:'pontos'}]}
  };

  function ensurePlannerState(){state.questProgress=state.questProgress||{};state.questPlans=state.questPlans||{};state.plannerDate=state.plannerDate||today();state.timelineDomain=state.timelineDomain||'Todos';state.timelineMonth=state.timelineMonth||today().slice(0,7)}
  ensurePlannerState();
  function copy(x){return JSON.parse(JSON.stringify(x))}
  function planFor(q){const base=BLUEPRINTS[q.id]?copy(BLUEPRINTS[q.id]):{},custom=state.questPlans[q.id]||{},merged=Object.assign({},base,custom);if(custom.subtasks)merged.subtasks=copy(custom.subtasks);return merged}
  function hasPlan(q){return(planFor(q).subtasks||[]).length>0}
  function progressKey(q,date=today()){const p=planFor(q);if(p.scope==='global')return q.id;if(p.scope==='monthly')return`${q.id}@${String(date).slice(0,7)}`;return occurrenceKey(q,date)}
  function progressState(q,date=today()){ensurePlannerState();const k=progressKey(q,date);state.questProgress[k]=state.questProgress[k]||{items:{},note:'',closedPct:null};state.questProgress[k].items=state.questProgress[k].items||{};return state.questProgress[k]}
  function subProgress(item,value){if(item.kind==='metric')return Math.max(0,Math.min(1,Number(value?.actual||0)/Math.max(1,Number(item.target||1))));return value?.done?1:0}
  function progressInfo(q,date=today()){const p=planFor(q),items=p.subtasks||[],s=progressState(q,date);if(!items.length)return{pct:done(q,date)?100:0,items:[],complete:done(q,date)};let sum=0,weight=0;items.forEach(item=>{const w=Number(item.weight||1);sum+=subProgress(item,s.items[item.id])*w;weight+=w});const pct=Math.round((weight?sum/weight:0)*100);return{pct,items,complete:pct>=100,state:s}}
  function fmtNumber(v,unit=''){const n=Number(v||0);if(unit==='R$')return`R$ ${n.toLocaleString('pt-BR')}`;return`${n.toLocaleString('pt-BR')}${unit?` ${unit}`:''}`}
  function progressHtml(q,date=today(),compact=false){const info=progressInfo(q,date);if(!info.items.length)return'';const closed=done(q,date),closedPct=info.state.closedPct;if(compact)return`<div class="smart-progress"><div><span>Progresso</span><b>${closed&&closedPct!==null?closedPct:info.pct}%</b></div><div class="progress"><i style="width:${closed&&closedPct!==null?closedPct:info.pct}%"></i></div></div>`;const rows=info.items.map(item=>{const val=info.state.items[item.id]||{};if(item.kind==='metric')return`<div class="subtask-row metric"><div class="subtask-main"><b>${esc(item.title)}</b><span>${fmtNumber(val.actual||0,item.unit)} / ${fmtNumber(item.target,item.unit)}</span></div><div class="metric-input"><input type="number" min="0" step="${item.unit==='R$'?'100':'1'}" value="${Number(val.actual||0)}" data-progress-metric="${esc(q.id)}" data-sub="${esc(item.id)}" data-date="${date}"><span>${esc(item.unit||'')}</span></div></div>`;return`<button class="subtask-row checkrow ${val.done?'on':''}" data-progress-check="${esc(q.id)}" data-sub="${esc(item.id)}" data-date="${date}"><span class="subcheck">✓</span><b>${esc(item.title)}</b></button>`}).join('');return`<details class="quest-breakdown" ${closed?'':'open'}><summary><span>Etapas / resultado real</span><b>${closed&&closedPct!==null?closedPct:info.pct}%</b></summary><div class="smart-progress"><div class="progress"><i style="width:${closed&&closedPct!==null?closedPct:info.pct}%"></i></div></div>${rows}<div class="result-note"><label>Resultado real / observações</label><textarea data-progress-note="${esc(q.id)}" data-date="${date}" placeholder="Ex.: 22 conversas, 3 indústrias realmente aderentes, próximo passo...">${esc(info.state.note||'')}</textarea></div>${!closed?`<button class="btn small ${info.pct>=100?'primary':''}" data-close-real="${esc(q.id)}" data-date="${date}">${info.pct>=100?'Concluir missão':'Encerrar com resultado real'}</button>`:''}</details>`}

  questCard=function(q,date=today(),compact=false){const is=done(q,date),ds=dependencyStatus(q),status=questStatusLabel(q,date),deps=ds.missing.map(id=>questById(id)?.title||id),smart=hasPlan(q),pi=smart?progressInfo(q,date):null;const meta=[`<span class="tag ${q.questType}">${q.questType==='main'?'MAIN QUEST':'SIDE QUEST'}</span>`,`<span class="tag ${q.domain}">${esc(q.domain)}</span>`,`<span class="pill">${cadenceLabel(q.cadence)}</span>`,q.timeStart?`<span class="pill blue">${esc(q.timeStart)}${q.timeEnd?'–'+esc(q.timeEnd):''}</span>`:'',q.dueDate?`<span class="pill ${q.dueDate<today()&&!is?'red':''}">⌛ ${fmt(q.dueDate)}</span>`:'',q.difficulty>=4?`<span class="pill amber">BOSS ${'★'.repeat(Math.min(5,q.difficulty))}</span>`:''].join('');const toggleAttr=smart?`data-smart-toggle="${esc(q.id)}"`:`data-toggle="${esc(q.id)}"`;const actualStatus=is&&smart&&pi.state.closedPct!==null&&pi.state.closedPct<100?`Encerrada ${pi.state.closedPct}%`:status;return`<article class="quest ${q.questType==='main'?'main':''} ${is?'done':''} ${ds.locked?'locked':''}"><div class="quest-head"><button class="check" ${toggleAttr} data-date="${date}" ${ds.locked?'disabled':''}>✓</button><div><div class="quest-title">${esc(q.title)}</div>${compact?'':`<div class="quest-desc">${esc(q.description||'')}</div>`}<div class="quest-meta">${meta}<span class="pill green">+${q.xp} XP</span>${smart?`<span class="pill violet">${pi.pct}% medido</span>`:''}${q.source?`<span class="pill">${esc(q.source)}</span>`:''}</div>${ds.locked?`<div class="subtle" style="margin-top:7px">🔒 Depende de: ${esc(deps.join(', '))}</div>`:''}${(q.correlations||[]).length?`<div class="subtle" style="margin-top:5px">🔗 Correlacionada: ${(q.correlations||[]).map(id=>esc(questById(id)?.title||id)).join(', ')}</div>`:''}${progressHtml(q,date,compact)}</div><div class="quest-actions"><span class="pill ${actualStatus==='Atrasada'?'red':is?'green':''}">${actualStatus}</span><button class="mini-link" data-plan="${esc(q.id)}">Etapas</button><button class="mini-link" data-edit="${esc(q.id)}">Editar</button></div></div></article>`};
  function storeProgress(q,date,sub,patch){const s=progressState(q,date);s.items[sub]=Object.assign({},s.items[sub]||{},patch);saveState()}
  function closeWithReal(id,date){const q=questById(id);if(!q)return;const info=progressInfo(q,date);if(done(q,date)){BASE_TOGGLE_QUEST(id,date);return}if(info.pct<100&&!confirm(`A meta está em ${info.pct}%. Encerrar a missão registrando o resultado real mesmo abaixo do alvo?`))return;info.state.closedPct=info.pct;saveState();BASE_TOGGLE_QUEST(id,date)}
  bindQuestCards=function(){BASE_BIND_QUEST_CARDS();document.querySelectorAll('[data-smart-toggle]').forEach(b=>b.onclick=()=>closeWithReal(b.dataset.smartToggle,b.dataset.date));document.querySelectorAll('[data-progress-check]').forEach(b=>b.onclick=()=>{const q=questById(b.dataset.progressCheck),s=progressState(q,b.dataset.date),cur=s.items[b.dataset.sub]?.done;storeProgress(q,b.dataset.date,b.dataset.sub,{done:!cur});render()});document.querySelectorAll('[data-progress-metric]').forEach(i=>i.onchange=()=>{const q=questById(i.dataset.progressMetric);storeProgress(q,i.dataset.date,i.dataset.sub,{actual:Math.max(0,Number(i.value||0))});render()});document.querySelectorAll('[data-progress-note]').forEach(t=>t.onchange=()=>{const q=questById(t.dataset.progressNote);progressState(q,t.dataset.date).note=t.value.trim();saveState()});document.querySelectorAll('[data-close-real]').forEach(b=>b.onclick=()=>closeWithReal(b.dataset.closeReal,b.dataset.date));document.querySelectorAll('[data-plan]').forEach(b=>b.onclick=()=>openPlanModal(b.dataset.plan))};

  function durationFor(q){const p=planFor(q);if(Number(p.durationMin)>0)return Number(p.durationMin);if(q.timeStart&&q.timeEnd){const d=toMin(q.timeEnd)-toMin(q.timeStart);if(d>0)return d}const text=`${q.title||''} ${q.description||''}`;let m=text.match(/(\d+)\s*min/i);if(m)return Number(m[1]);m=text.match(/(\d+(?:[.,]\d+)?)\s*h(?:ora|\b)/i);if(m)return Math.round(Number(m[1].replace(',','.'))*60);if(q.id==='personal-wake')return 15;if(q.id==='personal-breakfast')return 30;if(q.id==='personal-lunch')return 60;if(q.id==='personal-gym')return 90;if(q.id==='personal-leisure')return 60;if(q.id==='personal-sleep')return 15;if(q.id==='study-focus')return 90;if(q.id==='study-q25')return 60;if(q.id==='study-errors'||q.id==='study-basic')return 30;if(q.id==='study-boss')return 120;if(q.id==='study-postboss')return 60;if(q.domain==='Carreira')return 45;if(q.questType==='main')return 75;return DEFAULT_DURATION}
  function toMin(t){if(!t)return null;const[h,m]=String(t).split(':').map(Number);return h*60+(m||0)}
  function toTime(n){n=Math.max(0,Math.min(1439,Math.round(n)));return`${String(Math.floor(n/60)).padStart(2,'0')}:${String(n%60).padStart(2,'0')}`}
  function overlap(a,b){return a.start<b.end&&b.start<a.end}
  function desiredMinute(q,wake){if(q.timeStart)return toMin(q.timeStart);if(q.domain==='GSA'||q.domain==='Carreira')return Math.max(wake+120,9*60);if(q.domain==='Estudos')return 18*60;if(q.domain==='Pessoal')return 17*60;return wake+180}
  function urgency(q,date){let s=q.questType==='main'?1000:0;s+=(6-Number(q.difficulty||2))*-10;if(q.dueDate){const d=diffDays(date,q.dueDate);s+=d<=0?700:d<=3?500:d<=7?300:d<=14?150:0}if(hasPlan(q)){const p=progressInfo(q,date).pct;s+=Math.round((100-p)*2)}return s}
  function findSlot(desired,duration,occupied,start,end){const latest=end-duration,candidates=[];for(let t=Math.max(start,desired);t<=latest;t+=5)candidates.push(t);for(let t=start;t<Math.min(desired,latest+1);t+=5)candidates.push(t);for(const t of candidates){const slot={start:t,end:t+duration};if(!occupied.some(o=>overlap({start:slot.start-BUFFER_MIN,end:slot.end+BUFFER_MIN},o)))return slot}return null}
  function dayPlan(date){ensurePlannerState();const list=todayQuests(date),wakeQ=questById('personal-wake'),sleepQ=questById('personal-sleep');let wake=toMin(wakeQ?.timeStart)||7*60,preferredSleep=toMin(sleepQ?.timeStart);if(preferredSleep!==null&&preferredSleep<=wake)preferredSleep+=1440;const latestSleep=wake+MAX_AWAKE_MIN,sleepAt=Math.min(preferredSleep||latestSleep,latestSleep),end=Math.min(1439,sleepAt),start=wake,occupied=[],scheduled=[],overflow=[];function reserve(q,s,d,reason){if(!q||!list.some(x=>x.id===q.id))return;const slot={q,start:s,end:Math.min(end,s+d),reason,anchor:true};occupied.push({start:slot.start,end:slot.end});scheduled.push(slot)}reserve(wakeQ,start,durationFor(wakeQ),'âncora da jornada');const breakfast=questById('personal-breakfast'),lunch=questById('personal-lunch');if(breakfast)reserve(breakfast,Math.max(start+30,toMin(breakfast.timeStart)||8*60),durationFor(breakfast),'refeição protegida');if(lunch)reserve(lunch,toMin(lunch.timeStart)||12*60+30,durationFor(lunch),'refeição protegida');if(sleepQ&&list.some(x=>x.id===sleepQ.id)){const dur=durationFor(sleepQ);reserve(sleepQ,Math.max(start,end-dur),dur,preferredSleep&&preferredSleep>latestSleep?'ajustado para preservar 8h de sono':'meta de sono')}const anchorIds=new Set(scheduled.map(x=>x.q.id)),candidates=list.filter(q=>!anchorIds.has(q.id)).sort((a,b)=>desiredMinute(a,start)-desiredMinute(b,start)||urgency(b,date)-urgency(a,date));for(const q of candidates){const dur=durationFor(q),desired=Math.max(start,Math.min(end-dur,desiredMinute(q,start))),slot=findSlot(desired,dur,occupied,start,end);if(slot){occupied.push({start:slot.start,end:slot.end});scheduled.push({q,start:slot.start,end:slot.end,reason:q.timeStart&&slot.start!==toMin(q.timeStart)?`ajustado de ${q.timeStart} por conflito`:(q.timeStart?'horário preferido':'encaixe automático'),anchor:false})}else overflow.push({q,duration:dur})}scheduled.sort((a,b)=>a.start-b.start);const planned=scheduled.reduce((s,x)=>s+(x.end-x.start),0),available=Math.max(0,end-start);return{date,start,end,scheduled,overflow,planned,available,free:Math.max(0,available-planned),sleepAdjusted:preferredSleep&&preferredSleep>latestSleep}}
  function timelineItem(slot,date){const q=slot.q,pi=hasPlan(q)?progressInfo(q,date):null,is=done(q,date);return`<div class="day-slot ${q.questType==='main'?'main':''} ${is?'done':''}"><div class="slot-time"><b>${toTime(slot.start)}</b><span>${toTime(slot.end)}</span></div><div class="slot-body"><div class="slot-title"><button class="check" ${hasPlan(q)?`data-smart-toggle="${esc(q.id)}"`:`data-toggle="${esc(q.id)}"`} data-date="${date}" ${dependencyStatus(q).locked?'disabled':''}>✓</button><div><b>${esc(q.title)}</b><span>${esc(q.domain)} · ${Math.max(5,slot.end-slot.start)} min</span></div></div><div class="slot-reason">${esc(slot.reason)}${pi?` · ${pi.pct}% medido`:''}</div>${hasPlan(q)?progressHtml(q,date,true):''}</div><button class="mini-link" data-plan="${esc(q.id)}">Etapas</button></div>`}
  function smartRenderToday(){ensurePlannerState();const date=state.plannerDate||today(),p=dayPlan(date),doneN=todayQuests(date).filter(q=>done(q,date)).length,total=todayQuests(date).length;document.getElementById('view').innerHTML=`<div class="section-title planner-head"><div><span class="eyebrow">AGENDA PROGRAMÁTICA</span><h2>${date===today()?'Hoje':fmt(date,{weekday:'long',day:'2-digit',month:'long'})}</h2><p class="muted">Ordem preferencial calculada por horários, prioridade, deadlines e conflitos.</p></div><div class="day-nav"><button class="btn small" id="dayPrev">←</button><button class="btn small" id="dayNow">Hoje</button><button class="btn small" id="dayNext">→</button></div></div><div class="planner-stats"><div class="card mini-stat"><span>Janela acordado</span><b>${toTime(p.start)}–${toTime(p.end)}</b><small>${Math.round(p.available/60*10)/10}h · mínimo 8h de sono</small></div><div class="card mini-stat"><span>Carga planejada</span><b>${Math.floor(p.planned/60)}h ${p.planned%60}min</b><small>${p.free} min ainda livres</small></div><div class="card mini-stat ${p.overflow.length?'danger':''}"><span>Capacidade</span><b>${p.overflow.length?`${p.overflow.length} fora da agenda`:'Cabe no dia'}</b><small>${doneN}/${total} quests concluídas</small></div><div class="card mini-stat"><span>Score do dia</span><b>${dailyScore(date)}%</b><small>${p.sleepAdjusted?'Sono antecipado para preservar 8h':'Janela de sono protegida'}</small></div></div>${p.sleepAdjusted?`<div class="callout planner-warning">A missão de sono estava programada depois do limite de 16h acordado. A agenda recomenda encerrar às <b>${toTime(p.end)}</b> para proteger 8h de sono.</div>`:''}<div class="day-timeline">${p.scheduled.map(x=>timelineItem(x,date)).join('')||'<div class="empty">Nenhuma quest neste dia.</div>'}</div>${p.overflow.length?`<div class="card danger overflow-card"><span class="eyebrow">OVERLOAD</span><h2>Estas missões não cabem logicamente nas 16h</h2><p class="muted">Não empilhei tarefas impossíveis depois do horário de dormir. Reprograme, reduza duração ou mova uma Side Quest.</p>${p.overflow.map(x=>`<div class="overflow-row"><b>${esc(x.q.title)}</b><span>${x.duration} min · ${esc(x.q.domain)}</span><button class="mini-link" data-edit="${esc(x.q.id)}">Editar</button></div>`).join('')}</div>`:''}`;document.getElementById('dayPrev').onclick=()=>{state.plannerDate=addDays(date,-1);saveState();render()};document.getElementById('dayNow').onclick=()=>{state.plannerDate=today();saveState();render()};document.getElementById('dayNext').onclick=()=>{state.plannerDate=addDays(date,1);saveState();render()};bindQuestCards()}
  renderToday=smartRenderToday;

  function monthMove(ym,delta){const[y,m]=ym.split('-').map(Number),d=new Date(y,m-1+delta,1);return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`}
  function monthCalendar(ym){const[y,m]=ym.split('-').map(Number),first=new Date(y,m-1,1),offset=(first.getDay()+6)%7,days=new Date(y,m,0).getDate();let cells='';for(let i=0;i<offset;i++)cells+='<div class="month-cell blank"></div>';for(let d=1;d<=days;d++){const date=`${y}-${String(m).padStart(2,'0')}-${String(d).padStart(2,'0')}`,qs=todayQuests(date),dead=quests().filter(q=>q.dueDate===date&&!hasEverDone(q.id)),main=qs.filter(q=>q.questType==='main'&&!done(q,date)).length;cells+=`<button class="month-cell ${date===today()?'today':''}" data-calendar-day="${date}"><span class="month-num">${d}</span><span class="month-load">${qs.length} quests</span>${main?`<i class="dot main-dot" title="${main} Main Quests"></i>`:''}${dead.length?`<i class="dot deadline-dot" title="${dead.length} deadlines"></i>`:''}</button>`}return`<div class="month-grid"><div class="month-week">Seg</div><div class="month-week">Ter</div><div class="month-week">Qua</div><div class="month-week">Qui</div><div class="month-week">Sex</div><div class="month-week">Sáb</div><div class="month-week">Dom</div>${cells}</div>`}
  function ganttData(){const domain=state.timelineDomain||'Todos';let list=quests().filter(q=>q.dueDate&&(q.questType==='main'||q.cadence==='once'||q.cadence==='monthly'));if(domain!=='Todos')list=list.filter(q=>q.domain===domain);return list.sort((a,b)=>(a.startDate||a.dueDate).localeCompare(b.startDate||b.dueDate)||a.dueDate.localeCompare(b.dueDate))}
  function renderGantt(list){if(!list.length)return'<div class="empty">Nenhuma meta com prazo nesse filtro.</div>';const starts=list.map(q=>q.startDate||q.dueDate).sort(),ends=list.map(q=>q.dueDate).sort();let min=starts[0],max=ends[ends.length-1];if(diffDays(min,max)<31)max=addDays(min,31);const span=Math.max(1,diffDays(min,max)),monthMarks=[];let cursor=min.slice(0,7)+'-01';if(cursor<min)cursor=monthMove(min.slice(0,7),1)+'-01';while(cursor<=max){monthMarks.push(cursor);cursor=monthMove(cursor.slice(0,7),1)+'-01'}const scale=monthMarks.map(d=>{const left=Math.max(0,Math.min(100,diffDays(min,d)/span*100));return`<span style="left:${left}%">${dfrom(d).toLocaleDateString('pt-BR',{month:'short',year:'2-digit'})}</span>`}).join('');const rows=list.map(q=>{const a=q.startDate||q.dueDate,b=q.dueDate,left=Math.max(0,diffDays(min,a)/span*100),width=Math.max(1,Math.max(1,diffDays(a,b)+1)/span*100),pct=hasPlan(q)?progressInfo(q,today()).pct:(hasEverDone(q.id)?100:0),late=b<today()&&!hasEverDone(q.id);return`<div class="gantt-row"><div class="gantt-label"><b>${esc(q.title)}</b><span>${esc(q.domain)} · ${fmt(b)}</span></div><div class="gantt-track"><div class="gantt-bar ${q.questType==='main'?'main':''} ${late?'late':''}" style="left:${left}%;width:${width}%"><i style="width:${pct}%"></i><span>${pct}%</span></div></div></div>`}).join(''),todayPos=Math.max(0,Math.min(100,diffDays(min,today())/span*100));return`<div class="gantt-wrap"><div class="gantt-scale"><div></div><div class="gantt-scale-track">${scale}<i style="left:${todayPos}%"></i></div></div>${rows}</div>`}
  function renderTimeline(){ensurePlannerState();const ym=state.timelineMonth||today().slice(0,7),label=dfrom(ym+'-01').toLocaleDateString('pt-BR',{month:'long',year:'numeric'}),list=ganttData();document.getElementById('view').innerHTML=`<div class="section-title"><div><span class="eyebrow">CALENDÁRIO DE CAMPANHA</span><h2>${label}</h2><p class="muted">Carga diária, Main Quests e deadlines em uma visão; abaixo, a progressão temporal das metas.</p></div><div class="day-nav"><button class="btn small" id="monthPrev">←</button><button class="btn small" id="monthNow">Mês atual</button><button class="btn small" id="monthNext">→</button></div></div><div class="card calendar-card">${monthCalendar(ym)}<div class="calendar-legend"><span><i class="dot main-dot"></i>Main Quest no dia</span><span><i class="dot deadline-dot"></i>Deadline</span><span>Clique em um dia para abrir a agenda programática.</span></div></div><div class="section-title"><div><span class="eyebrow">GANTT</span><h2>Progressão das metas</h2><p class="muted">Barra = janela da meta; preenchimento = progresso medido ou conclusão.</p></div><select id="timelineDomain" class="timeline-filter">${['Todos','Pessoal','GSA','Estudos','Carreira'].map(x=>`<option ${state.timelineDomain===x?'selected':''}>${x}</option>`).join('')}</select></div>${renderGantt(list)}`;document.getElementById('monthPrev').onclick=()=>{state.timelineMonth=monthMove(ym,-1);saveState();render()};document.getElementById('monthNow').onclick=()=>{state.timelineMonth=today().slice(0,7);saveState();render()};document.getElementById('monthNext').onclick=()=>{state.timelineMonth=monthMove(ym,1);saveState();render()};document.getElementById('timelineDomain').onchange=e=>{state.timelineDomain=e.target.value;saveState();render()};document.querySelectorAll('[data-calendar-day]').forEach(b=>b.onclick=()=>{state.plannerDate=b.dataset.calendarDay;state.view='today';saveState();render();window.scrollTo({top:0,behavior:'smooth'})})}

  function openPlanModal(id){const q=questById(id);if(!q)return;const p=planFor(q),items=p.subtasks||[];document.getElementById('modal').innerHTML=`<div class="modal-wrap"><div class="modal-card smart-modal"><div class="modal-head"><div><span class="eyebrow">QUEBRAR META</span><h2>${esc(q.title)}</h2></div><button class="close" id="closePlan">×</button></div><p class="muted">Defina duração e etapas. Métricas aceitam o valor real obtido e preservam resultados parciais.</p><div class="form-row"><div class="field"><label>Duração planejada por bloco (min)</label><input id="planDuration" type="number" min="5" step="5" value="${Number(p.durationMin||durationFor(q))}"></div><div class="field"><label>Escopo do progresso</label><select id="planScope"><option value="period" ${!p.scope||p.scope==='period'?'selected':''}>Por ocorrência / período</option><option value="monthly" ${p.scope==='monthly'?'selected':''}>Reinicia a cada mês</option><option value="global" ${p.scope==='global'?'selected':''}>Acumulado até concluir</option></select></div></div><div id="planRows">${items.map(planRow).join('')}</div><button class="btn small" id="addPlanRow">+ Etapa</button><div class="modal-actions"><button class="btn" id="cancelPlan">Cancelar</button><button class="btn primary" id="savePlan">Salvar etapas</button></div></div></div>`;function bindRemove(){document.querySelectorAll('[data-plan-remove]').forEach(b=>b.onclick=()=>b.closest('.plan-row').remove())}bindRemove();document.getElementById('addPlanRow').onclick=()=>{document.getElementById('planRows').insertAdjacentHTML('beforeend',planRow({id:'step-'+Date.now(),title:'Nova etapa',kind:'check',target:1,unit:''}));bindRemove()};document.getElementById('closePlan').onclick=document.getElementById('cancelPlan').onclick=closeModal;document.getElementById('savePlan').onclick=()=>{const subtasks=[...document.querySelectorAll('.plan-row')].map((r,i)=>({id:r.dataset.step||`step-${Date.now()}-${i}`,title:r.querySelector('[data-title]').value.trim()||`Etapa ${i+1}`,kind:r.querySelector('[data-kind]').value,target:Math.max(1,Number(r.querySelector('[data-target]').value||1)),unit:r.querySelector('[data-unit]').value.trim()}));state.questPlans[id]={durationMin:Math.max(5,Number(document.getElementById('planDuration').value||45)),scope:document.getElementById('planScope').value,subtasks};saveState();closeModal();render();toast('Etapas e duração atualizadas')}}
  function planRow(item){return`<div class="plan-row" data-step="${esc(item.id||'')}"><input data-title value="${esc(item.title||'')}"><select data-kind><option value="check" ${item.kind!=='metric'?'selected':''}>Checklist</option><option value="metric" ${item.kind==='metric'?'selected':''}>Métrica</option></select><input data-target type="number" min="1" value="${Number(item.target||1)}"><input data-unit placeholder="unidade" value="${esc(item.unit||'')}"><button class="mini-link" data-plan-remove>×</button></div>`}

  render=function(){if(state.view==='timeline'){renderHud();renderTimeline();document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===state.view));window.dispatchEvent(new CustomEvent('my-performance-view-rendered',{detail:{view:state.view}}));return}BASE_RENDER()};
  document.querySelectorAll('[data-view="timeline"]').forEach(b=>b.onclick=()=>go('timeline'));
  render();
})();
