const BUILD='2.9.3';
const CACHE='my-performance-v2.9.3';
const ASSETS=['./','./index.html','./preboot-compact-v12.js','./boot-ready-v11.css','./styles.css','./planner.css','./narrator.css','./calendar-v3.css','./calendar-v5.css','./calendar-v5-interactions.css','./ui-polish-v6.css','./weekly-config-v7.css','./interactive-week-config-v8.css','./config-polish-v9.css','./group-root-v10.css','./sidequest-priority-v11.css','./calendar-timeline-v11.css','./temporal-execution-v8.css','./today-only-v13.css','./config-performance-v1.css','./data.js','./routine-data.js','./app.js','./quest-repository-v1.js','./sp-clock-v6.js','./scheduler-core.js','./planner.js','./calendar-model-v3.js','./campaign-policy-v3.js','./calendar-model-fastpath-v4.js','./state-revision-prune-v8.js','./calendar-domain-v5.js','./calendar-revision-safety-v8.js','./calendar-mutation-bounded-v9.js','./calendar-groups-v7.js','./quest-audit-v6.js','./taxonomy-fillers-v10.js','./quest-milestones-v6.js','./quantitative-mainquests-v6.js','./calendar-persistence-v5.js','./calendar-planner-policy-v5.js','./planner-dependency-v5.js','./sidequest-quality-v5.js','./planner-engine-v5.js','./planning-context-v1.js','./planner-group-integrity-v5.js','./sidequest-priority-v11.js','./sidequest-bulk-v10.js','./routine-anchors-v7.js','./day-frame-v5.js','./day-frame-clock-v8.js','./wake-time-ui-v6.js','./opportunistic-sidequests-v5.js','./sidequest-lane-authority-v13.js','./calendar-actions-v5.js','./calendar-runtime-v3.js','./cloud-gateway-v1.js','./cloud-sync-v2.js','./notifications.js','./pwa-update.js','./calendar-ui-v5.js','./temporal-execution-v8.js','./temporal-consistency-v11.js','./temporal-execution-ui-v8.js','./modal-ui-fix-v5.js','./mission-context-v5.js','./routine-side-policy-v7.js','./fragment-progress-v6.js','./weekly-config-ui-v7.js','./interactive-week-config-v8.js','./sidequest-duration-v9.js','./filler-ui-v10.js','./daily-review-v6.js','./calendar-advanced-v5.js','./mainquest-grouped-config-v9.js','./sidequest-bulk-ui-v10.js','./group-root-config-v10.js','./group-root-extras-v10.js','./sidequest-priority-ui-v11.js','./window-authority-v11.js','./calendar-timeline-v11.js','./calendar-strategic-v5.js','./today-only-runtime-v13.js','./retired-views-v6.js','./runtime-stability-v5.js','./config-performance-v1.js','./runtime-performance-v14.js','./performance-observability-v1.js','./boot-ready-v11.js','./version.json','./manifest.webmanifest','./icon.svg'];
self.addEventListener('install',event=>event.waitUntil(caches.open(CACHE).then(cache=>cache.addAll(ASSETS)).then(()=>self.skipWaiting())));
self.addEventListener('activate',event=>event.waitUntil((async()=>{const keys=await caches.keys();await Promise.all(keys.filter(key=>key.startsWith('my-performance-')&&key!==CACHE).map(key=>caches.delete(key)));await self.clients.claim();const windows=await self.clients.matchAll({type:'window',includeUncontrolled:true});await Promise.all(windows.map(async client=>{try{const u=new URL(client.url);if(u.origin!==self.location.origin)return;if(u.searchParams.get('_mpv')===BUILD)return;u.searchParams.set('_mpv',BUILD);u.searchParams.set('_mpr',Date.now().toString());await client.navigate(u.toString())}catch{}}))})()));
self.addEventListener('message',event=>{if(event.data?.type==='SKIP_WAITING')self.skipWaiting()});
self.addEventListener('fetch',event=>{
  if(event.request.method!=='GET')return;
  const url=new URL(event.request.url);
  if(url.origin!==self.location.origin)return;
  if(url.pathname.startsWith('/api/'))return;
  if(event.request.mode==='navigate'){
    event.respondWith((async()=>{try{const response=await fetch(event.request,{cache:'no-store'});if(response&&response.ok){const cache=await caches.open(CACHE);cache.put('./index.html',response.clone());return response}}catch{}return(await caches.match('./index.html'))||(await caches.match('./'))||Response.error()})());return;
  }
  if(url.pathname.endsWith('/version.json')){event.respondWith(fetch(event.request,{cache:'no-store'}).catch(()=>caches.match(event.request)));return}
  event.respondWith(caches.match(event.request).then(hit=>hit||fetch(event.request).then(response=>{if(response&&response.ok){const copy=response.clone();caches.open(CACHE).then(cache=>cache.put(event.request,copy))}return response})))
});
