const fs=require('fs'),vm=require('vm'),assert=require('assert');
const listeners={};const ctx={console,Date,JSON,Math,setTimeout:()=>0,clearTimeout:()=>{},requestAnimationFrame:()=>0,CustomEvent:function(type,init){this.type=type;this.detail=init?.detail},localStorage:{getItem(){return null},setItem(){}},state:{completed:{},xpLedger:{},bonusLedger:{},activityDates:[],customQuests:[],overrides:{},questPlans:{},filters:{domain:'Todos'},view:'today',plannerDate:'2026-08-11'},DOMAIN_META:{Pessoal:{},GSA:{},Estudos:{},Carreira:{}},QUEST_SEED:[]};ctx.globalThis=ctx;ctx.window=ctx;ctx.addEventListener=(t,f)=>(listeners[t]||(listeners[t]=[])).push(f);ctx.dispatchEvent=e=>{for(const f of listeners[e.type]||[])f(e)};ctx.iso=d=>{const x=new Date(d||Date.now());x.setMinutes(x.getMinutes()-x.getTimezoneOffset());return x.toISOString().slice(0,10)};ctx.dfrom=s=>new Date(`${s}T12:00:00`);ctx.today=()=> '2026-08-11';ctx.addDays=(s,n)=>{const d=ctx.dfrom(s);d.setDate(d.getDate()+n);return ctx.iso(d)};ctx.diffDays=(a,b)=>Math.round((ctx.dfrom(b)-ctx.dfrom(a))/864e5);ctx.weekStart=s=>{const d=ctx.dfrom(s),n=(d.getDay()+6)%7;d.setDate(d.getDate()-n);return ctx.iso(d)};ctx.saveState=()=>ctx.dispatchEvent(new ctx.CustomEvent('my-performance-state-saved',{detail:ctx.state}));ctx.Q=o=>ctx.QUEST_SEED.push(Object.assign({domain:'Pessoal',questType:'side',cadence:'once',weekdays:[],xp:20,difficulty:1},o));
[
{id:'personal-wake',title:'Acordar',domain:'Pessoal',cadence:'daily',weekdays:[1,2,3,4,5,6],durationMin:10},
{id:'personal-breakfast',title:'Café',domain:'Pessoal',cadence:'daily',weekdays:[1,2,4,5,6],durationMin:20},
{id:'personal-gym',title:'Academia',domain:'Pessoal',cadence:'daily',weekdays:[1,2,3,4,5,6],durationMin:90},
{id:'routine-shower-post-gym',title:'Banho',domain:'Pessoal',cadence:'daily',weekdays:[1,2,3,4,5,6],durationMin:30},
{id:'personal-lunch',title:'Almoço',domain:'Pessoal',cadence:'daily',weekdays:[1,2,3,4,5,6],durationMin:60},
{id:'routine-dinner',title:'Jantar',domain:'Pessoal',cadence:'daily',weekdays:[1,2,3,4],durationMin:30},
{id:'routine-hygiene-am',title:'Higiene',domain:'Pessoal',cadence:'daily',weekdays:[1,2,4,5,6],durationMin:10},
{id:'routine-hygiene-night',title:'Higiene sono',domain:'Pessoal',cadence:'daily',weekdays:[1,2,3,4],durationMin:15},
{id:'personal-sleep',title:'Dormir',domain:'Pessoal',cadence:'daily',weekdays:[1,2,3,4],durationMin:10},
{id:'gsa-critical',title:'Entrega GSA crítica',description:'Entrega grande que não cabe integralmente hoje.',domain:'GSA',category:'Editais',questType:'main',cadence:'once',startDate:'2026-08-10',dueDate:'2026-08-11',durationMin:600,priorityLevel:'critical'}
].forEach(ctx.Q);
ctx.quests=()=>ctx.QUEST_SEED.concat(ctx.state.customQuests||[]).map(q=>Object.assign({},q,ctx.state.overrides[q.id]||{})).filter(q=>!q.disabled);ctx.questById=id=>ctx.quests().find(q=>q.id===id);ctx.done=(q,date)=>!!ctx.state.completed[q.id];ctx.hasEverDone=id=>!!ctx.state.completed[id];ctx.scheduled=()=>true;
vm.createContext(ctx);for(const f of ['calendar-model-v3.js','calendar-model-fastpath-v4.js','calendar-domain-v5.js','calendar-persistence-v5.js','calendar-planner-policy-v5.js','planner-dependency-v5.js','sidequest-quality-v5.js','planner-engine-v5.js','planner-group-integrity-v5.js','day-frame-v5.js'])vm.runInContext(fs.readFileSync(f,'utf8'),ctx);
const E=ctx.MyPerformancePlannerEngine,D=ctx.MyPerformanceCalendarDomain,F=ctx.MyPerformanceDayFrame;assert(E&&D&&F);
let p=E.planDay('2026-08-11');const bad=p.slots.filter(s=>s.q?.id==='gsa-critical'&&s.start>=360&&s.start<540);assert.strictEqual(bad.length,0,'GSA Main Quest must never invade the Pessoal-only 06:00–09:00 health window, even when critical');assert(p.slots.some(s=>s.q?.id==='gsa-critical'&&s.group==='GSA'),'critical GSA work should remain in GSA-compatible windows when capacity exists');
D.addSideQuest('pack-piano',{id:'side-study-window',title:'Revisão leve',domain:'Estudos',cadence:'daily',weekdays:[2],durationMin:30,sideMeta:{packId:'pack-piano',active:true,rigidity:'free',windowMode:'exclusive',windowIds:['tue-study'],durationMode:'flexible',flexMinMin:10,flexMaxMin:30}});p=E.planDay('2026-08-11');const routed=p.slots.filter(s=>s.q?.id==='side-study-window');assert(routed.every(s=>s.windowId==='tue-study'),'Side Quest restricted to a window must not leak to other windows');assert(routed.every(s=>s.group==='Estudos'),'public Side Quest group must remain human-readable');
F.wakeNow('2026-08-11',600);p=E.planDay('2026-08-11');assert(p.slots.some(s=>s.event?.systemFrame&&s.start===360&&s.end===600),'late wake must create a date-specific unavailability block');assert(!p.slots.some(s=>!s.fixed&&!s.eventSlot&&!s.eventTravel&&s.start<600),'movable work must be replanned after the actual wake time');
F.extendDay('2026-08-11',120);p=E.planDay('2026-08-11');assert(p.windows.some(w=>w.dayExtension),'two-hour extension must appear as an explicit calendar window');assert(p.slots.some(s=>s.daySleepAnchor),'extended day must replace the normal sleep occurrence with a visible sleep anchor');assert(ctx.state.calendarV5.skippedDaily['2026-08-11']['personal-sleep@2026-08-11']===true,'normal sleep occurrence must be suppressed only for the extended date');
F.reset('2026-08-11');p=E.planDay('2026-08-11');assert(!p.windows.some(w=>w.dayExtension),'reset must remove the one-off extension');console.log('Calendar V5 strict groups, Side Quest windows and day-frame regression passed');
