const fs=require('fs'),assert=require('assert');
const ui=fs.readFileSync('calendar-ui-v5.js','utf8'),css=fs.readFileSync('calendar-v5.css','utf8'),domain=fs.readFileSync('calendar-domain-v5.js','utf8'),engine=fs.readFileSync('planner-engine-v5.js','utf8'),actions=fs.readFileSync('calendar-actions-v5.js','utf8'),index=fs.readFileSync('index.html','utf8'),sw=fs.readFileSync('sw.js','utf8'),version=require('../version.json');
assert.strictEqual(version.version,'2.1.0');assert(index.includes('data-build="2.1.0"'));for(const a of ['calendar-domain-v5.js','planner-engine-v5.js','calendar-actions-v5.js','calendar-ui-v5.js','calendar-v5.css','runtime-stability-v5.js'])assert(index.includes(a),`missing ${a}`);assert(index.indexOf('planner-engine-v5.js')<index.indexOf('calendar-actions-v5.js'));assert(index.indexOf('calendar-actions-v5.js')<index.indexOf('calendar-ui-v5.js'));for(const a of ['planner-engine-v4.js','calendar-ui-v3.js','runtime-stability-v4.js'])assert(!index.includes(`<script src="${a}"></script>`),`obsolete runtime loaded ${a}`);
for(const t of ['SIDE QUEST PACKS','EVENTOS','Janelas de capacidade','Fora do calendário','Substituir','Replanejar para frente','Preencher com Side Quest','MODO FOCO','FIXAÇÃO MANUAL','SEMANA ESTRATÉGICA','Simulação antes de aplicar'])assert(ui.includes(t),`UI contract missing ${t}`);
for(const t of ['window-band','window-rail','type-badge.main','type-badge.side','type-badge.event','outside-item','week-strategy'])assert(css.includes(t),`visual contract missing ${t}`);
for(const t of ['pack-piano','pack-leisure','pack-daily-life','pack-health','event-therapy','event-bni','event-zion','allowSideQuests','sideQuestDedicated','protectedWeeklyMinutes','decisionLog','revisions'])assert(domain.includes(t),`domain contract missing ${t}`);
for(const t of ['function eventSlots','function workItems','function strategicWeek','function substitute','function deferOutside','function pinSlot','calendar-v5'])assert(engine.includes(t),`planner contract missing ${t}`);for(const t of ['function discardDay','function restoreDay','function previewEvent','MyPerformanceCalendarActions'])assert(actions.includes(t),`actions contract missing ${t}`);
for(const t of ["BUILD='2.1.0'","CACHE='my-performance-v2.1.0'",'calendar-domain-v5.js','planner-engine-v5.js','calendar-actions-v5.js','calendar-ui-v5.js','calendar-v5.css'])assert(sw.includes(t),`PWA missing ${t}`);
console.log('Calendar V5 UI/domain/runtime contract passed');
