const fs=require('fs'),vm=require('vm'),assert=require('assert');
const listeners={};
const ctx={console,Date,JSON,Math,setTimeout:()=>0,clearTimeout:()=>{},CustomEvent:function(type,init){this.type=type;this.detail=init?.detail},localStorage:{m:new Map(),getItem(k){return this.m.get(k)||null},setItem(k,v){this.m.set(k,String(v))}},state:{completed:{},xpLedger:{},bonusLedger:{},activityDates:[],customQuests:[],overrides:{},questPlans:{},filters:{domain:'Todos'}},DOMAIN_META:{Pessoal:{},GSA:{},Estudos:{},Carreira:{}},QUEST_SEED:[]};
ctx.globalThis=ctx;ctx.window=ctx;ctx.addEventListener=(type,fn)=>(listeners[type]||(listeners[type]=[])).push(fn);ctx.dispatchEvent=e=>{for(const fn of listeners[e.type]||[])fn(e)};ctx.iso=d=>{const x=new Date(d||Date.now());x.setMinutes(x.getMinutes()-x.getTimezoneOffset());return x.toISOString().slice(0,10)};ctx.dfrom=s=>new Date(`${s}T12:00:00`);ctx.today=()=> '2026-08-11';ctx.addDays=(s,n)=>{const d=ctx.dfrom(s);d.setDate(d.getDate()+n);return ctx.iso(d)};ctx.diffDays=(a,b)=>Math.round((ctx.dfrom(b)-ctx.dfrom(a))/864e5);ctx.weekStart=s=>{const d=ctx.dfrom(s),n=(d.getDay()+6)%7;d.setDate(d.getDate()-n);return ctx.iso(d)};ctx.saveState=()=>{ctx.localStorage.setItem('my_performance_v1',JSON.stringify(ctx.state));ctx.dispatchEvent(new ctx.CustomEvent('my-performance-state-saved',{detail:ctx.state}))};ctx.Q=o=>ctx.QUEST_SEED.push(Object.assign({domain:'Pessoal',questType:'side',cadence:'once',weekdays:[],xp:20,difficulty:1},o));
[
{id:'personal-wake',title:'Acordar',domain:'Pessoal',cadence:'daily',weekdays:[1,2,3,4,5,6],durationMin:10},
{id:'routine-water-am',title:'Água',domain:'Pessoal',cadence:'daily',weekdays:[1,2,4,5,6],durationMin:5},
{id:'routine-hygiene-am',title:'Higiene',domain:'Pessoal',cadence:'daily',weekdays:[1,2,4,5,6],durationMin:10},
{id:'personal-breakfast',title:'Café',domain:'Pessoal',cadence:'daily',weekdays:[1,2,4,5,6],durationMin:30},
{id:'personal-gym',title:'Academia',domain:'Pessoal',cadence:'daily',weekdays:[1,2,3,4,5,6],timeStart:'06:30',fixedTime:true,durationMin:90},
{id:'routine-shower-post-gym',title:'Banho',domain:'Pessoal',cadence:'daily',weekdays:[1,2,3,4,5,6],timeStart:'08:00',fixedTime:true,durationMin:30},
{id:'personal-lunch',title:'Almoço',domain:'Pessoal',cadence:'daily',weekdays:[1,2,3,4,5,6],durationMin:30},
{id:'routine-dinner',title:'Jantar',domain:'Pessoal',cadence:'daily',weekdays:[1,2,3,4],durationMin:30},
{id:'routine-hygiene-night',title:'Higiene sono',domain:'Pessoal',cadence:'daily',weekdays:[1,2,3,4],durationMin:15},
{id:'personal-sleep',title:'Dormir',domain:'Pessoal',cadence:'daily',weekdays:[1,2,3,4],durationMin:10},
{id:'personal-evening-activity',title:'Atividade pessoal',domain:'Pessoal',cadence:'daily',weekdays:[1,2,3,4],durationMin:30},
{id:'study-main',title:'Estudar concurso',domain:'Estudos',questType:'main',cadence:'once',startDate:'2026-08-10',dueDate:'2026-11-30',durationMin:600,priorityLevel:'critical'},
{id:'gsa-main',title:'Main Quest GSA',domain:'GSA',category:'EVA',questType:'main',cadence:'once',startDate:'2026-08-10',dueDate:'2026-08-20',durationMin:300,priorityLevel:'high'}
].forEach(ctx.Q);
ctx.quests=()=>ctx.QUEST_SEED.concat(ctx.state.customQuests||[]).map(q=>Object.assign({},q,ctx.state.overrides[q.id]||{})).filter(q=>!q.disabled);ctx.questById=id=>ctx.quests().find(q=>q.id===id);ctx.scheduled=(q,date)=>{if(q.startDate&&date<q.startDate)return false;const wd=ctx.dfrom(date).getDay();if(q.cadence==='daily'||q.cadence==='weekly')return !(q.weekdays||[]).length||(q.weekdays||[]).includes(wd);if(q.cadence==='monthly')return true;if(q.cadence==='once')return !ctx.state.completed[q.id]&&date>=(q.startDate||date)&&date<=(q.dueDate||date);return false};ctx.occurrenceKey=(q,date)=>q.cadence==='daily'?`${q.id}@${date}`:q.cadence==='weekly'?`${q.id}@${ctx.weekStart(date)}`:q.id;ctx.done=(q,date)=>!!ctx.state.completed[ctx.occurrenceKey(q,date)];ctx.hasEverDone=id=>Object.keys(ctx.state.completed).some(k=>k===id||k.startsWith(id+'@'));
vm.createContext(ctx);for(const file of ['calendar-model-v3.js','calendar-model-fastpath-v4.js','calendar-domain-v5.js','planner-engine-v5.js'])vm.runInContext(fs.readFileSync(file,'utf8'),ctx);
const D=ctx.MyPerformanceCalendarDomain,E=ctx.MyPerformancePlannerEngine,B=ctx.MyPerformanceCalendarModel;assert(D&&D.VERSION===5);assert(E&&E.VERSION===5);
assert.deepStrictEqual(Array.from(B.groups().map(x=>x.id)),['GSA','Estudos','Pessoal']);
assert.strictEqual(D.model().sideQuestPacks.length>=4,true);for(const id of ['pack-piano','pack-leisure','pack-daily-life','pack-health'])assert(D.pack(id),`missing pack ${id}`);
for(const id of ['event-therapy','event-bni','event-zion'])assert(D.event(id),`missing event ${id}`);assert.strictEqual(ctx.questById('personal-therapy-weekly'),undefined,'legacy therapy quest must be disabled');
const therapy=D.event('event-therapy');assert.strictEqual(therapy.travelBeforeMin,60);assert.strictEqual(therapy.travelAfterMin,30);
const tue=E.planDay('2026-08-11');const ev=tue.slots.find(x=>x.eventId==='event-therapy'&&x.eventSlot),gym=tue.slots.find(x=>x.q?.id==='personal-gym');assert(ev&&ev.start===480&&ev.end===510,'therapy event must be 08:00-08:30');assert(tue.slots.some(x=>x.eventId==='event-therapy'&&x.eventTravel&&x.start===420&&x.end===480),'therapy travel before missing');assert(tue.slots.some(x=>x.eventId==='event-therapy'&&x.eventTravel&&x.start===510&&x.end===540),'therapy travel after missing');assert(gym&&gym.start===720&&gym.end===810,'Tuesday gym should prefer 12:00-13:30');assert.strictEqual(tue.slots.filter(x=>x.q?.id==='personal-gym').length,1,'gym duplicated');for(let i=1;i<tue.slots.length;i++)assert(tue.slots[i-1].end<=tue.slots[i].start,`overlap ${tue.slots[i-1].id}/${tue.slots[i].id}`);
const wed=E.planDay('2026-08-12');assert(wed.slots.some(x=>x.eventId==='event-bni'&&x.eventSlot&&x.start===360&&x.end===660),'BNI event missing');const thu=E.planDay('2026-08-13');assert(thu.slots.some(x=>x.eventId==='event-zion'&&x.eventSlot&&x.start===1140&&x.end===1380),'Zion event missing');
const dailyLunch=tue.slots.filter(x=>x.q?.id==='personal-lunch');assert(dailyLunch.length<=1,'daily Side Quest must never stack');
D.togglePack('pack-health',false);const tueNoHealth=E.planDay('2026-08-11');assert(!tueNoHealth.slots.some(x=>x.q?.id==='personal-gym'),'disabled pack must remove its Side Quests');D.togglePack('pack-health',true);
const w=D.windowForId('tue-gsa-1');D.updateWindow(w.id,{allowSideQuests:false,sideQuestDedicated:false});assert.strictEqual(D.windowForId(w.id).allowSideQuests,false);
const outside=E.planDay('2026-08-11').outsideCalendar;assert(Array.isArray(outside),'outside calendar must exist');
const preview=E.previewEvent({id:'preview-doctor',title:'Médico',type:'Outro',groupId:'Pessoal',recurrence:'once',date:'2026-08-11',start:'10:00',end:'11:00',travelRequired:true,travelBeforeMin:30,travelAfterMin:30,active:true});assert(preview.occurrences.length===1&&preview.occurrences[0].start===570&&preview.occurrences[0].end===690,'event preview must include travel');
const deadline=ctx.questById('gsa-main').dueDate;E.discardDay('2026-08-11');assert(E.planDay('2026-08-11').discarded);assert.strictEqual(ctx.questById('gsa-main').dueDate,deadline,'discard day cannot move deadline');
console.log('Calendar V5 functional regression passed');
