const fs=require('fs'),vm=require('vm'),assert=require('assert');
const listeners={};const ctx={console,Date,JSON,Math,setTimeout:()=>0,clearTimeout:()=>{},CustomEvent:function(type,init){this.type=type;this.detail=init?.detail},localStorage:{getItem(){return null},setItem(){}},state:{completed:{},xpLedger:{},bonusLedger:{},activityDates:[],customQuests:[],overrides:{},questPlans:{},filters:{domain:'Todos'}},DOMAIN_META:{Pessoal:{},GSA:{},Estudos:{},Carreira:{}},QUEST_SEED:[]};ctx.globalThis=ctx;ctx.window=ctx;ctx.addEventListener=(t,f)=>(listeners[t]||(listeners[t]=[])).push(f);ctx.dispatchEvent=e=>{for(const f of listeners[e.type]||[])f(e)};ctx.iso=d=>{const x=new Date(d||Date.now());x.setMinutes(x.getMinutes()-x.getTimezoneOffset());return x.toISOString().slice(0,10)};ctx.dfrom=s=>new Date(`${s}T12:00:00`);ctx.today=()=> '2026-08-11';ctx.addDays=(s,n)=>{const d=ctx.dfrom(s);d.setDate(d.getDate()+n);return ctx.iso(d)};ctx.diffDays=(a,b)=>Math.round((ctx.dfrom(b)-ctx.dfrom(a))/864e5);ctx.weekStart=s=>{const d=ctx.dfrom(s),n=(d.getDay()+6)%7;d.setDate(d.getDate()-n);return ctx.iso(d)};ctx.saveState=()=>ctx.dispatchEvent(new ctx.CustomEvent('my-performance-state-saved',{detail:ctx.state}));ctx.Q=o=>ctx.QUEST_SEED.push(Object.assign({domain:'Pessoal',questType:'side',cadence:'once',weekdays:[],xp:20,difficulty:1},o));
[
{id:'personal-wake',title:'Acordar',domain:'Pessoal',cadence:'daily',weekdays:[1,2,3,4,5,6],durationMin:10},{id:'personal-breakfast',title:'Café',domain:'Pessoal',cadence:'daily',weekdays:[1,2,4,5,6],durationMin:20},{id:'personal-gym',title:'Academia',domain:'Pessoal',cadence:'daily',weekdays:[1,2,3,4,5,6],durationMin:90},{id:'routine-shower-post-gym',title:'Banho',domain:'Pessoal',cadence:'daily',weekdays:[1,2,3,4,5,6],durationMin:30},{id:'personal-lunch',title:'Almoço',domain:'Pessoal',cadence:'daily',weekdays:[1,2,3,4,5,6],durationMin:30},{id:'routine-dinner',title:'Jantar',domain:'Pessoal',cadence:'daily',weekdays:[1,2,3,4],durationMin:30},{id:'routine-hygiene-am',title:'Higiene',domain:'Pessoal',cadence:'daily',weekdays:[1,2,4,5,6],durationMin:10},{id:'routine-hygiene-night',title:'Higiene sono',domain:'Pessoal',cadence:'daily',weekdays:[1,2,3,4],durationMin:15},{id:'personal-sleep',title:'Dormir',domain:'Pessoal',cadence:'daily',weekdays:[1,2,3,4],durationMin:10},
{id:'dep-a',title:'Preparar documentação',domain:'GSA',category:'Editais',questType:'main',cadence:'once',startDate:'2026-08-10',dueDate:'2026-08-20',durationMin:60,priorityLevel:'high'},
{id:'dep-b',title:'Enviar proposta',domain:'GSA',category:'Editais',questType:'main',cadence:'once',startDate:'2026-08-10',dueDate:'2026-08-20',durationMin:60,priorityLevel:'high',dependencies:['dep-a']}
].forEach(ctx.Q);
ctx.quests=()=>ctx.QUEST_SEED.concat(ctx.state.customQuests||[]).map(q=>Object.assign({},q,ctx.state.overrides[q.id]||{})).filter(q=>!q.disabled);ctx.questById=id=>ctx.quests().find(q=>q.id===id);ctx.done=(q,date)=>!!ctx.state.completed[q.id];ctx.hasEverDone=id=>!!ctx.state.completed[id];ctx.scheduled=()=>true;
vm.createContext(ctx);for(const f of ['calendar-model-v3.js','calendar-model-fastpath-v4.js','calendar-domain-v5.js','calendar-persistence-v5.js','calendar-planner-policy-v5.js','planner-dependency-v5.js','planner-engine-v5.js','planner-group-integrity-v5.js'])vm.runInContext(fs.readFileSync(f,'utf8'),ctx);
const E=ctx.MyPerformancePlannerEngine,Deps=ctx.MyPerformancePlannerDependencies,B=ctx.MyPerformanceCalendarModel;assert(E&&Deps);const depB=ctx.questById('dep-b');assert.strictEqual(Deps.status(depB).ready,false);assert.strictEqual(B.groupForQuest(depB),'GSA','dependency state must never replace the real Group');let p=E.planDay('2026-08-11');assert(!p.slots.some(x=>x.q?.id==='dep-b'),'dependent Main Quest cannot be scheduled before predecessor completion');assert(!p.outsideCalendar.some(x=>x.q?.id==='dep-b'),'blocked Main Quest should stay out of Today and remain visible only in Config as blocked');ctx.state.completed['dep-a']=true;ctx.saveState();assert.strictEqual(Deps.status(ctx.questById('dep-b')).ready,true);p=E.planDay('2026-08-11');assert(p.slots.some(x=>x.q?.id==='dep-b')||p.outsideCalendar.some(x=>x.q?.id==='dep-b'&&x.group==='GSA'),'dependency completion must restore scheduling eligibility');
ctx.Q({id:'cycle-a',title:'Cycle A',domain:'GSA',questType:'main',cadence:'once',startDate:'2026-08-10',dueDate:'2026-08-20',dependencies:['cycle-b']});ctx.Q({id:'cycle-b',title:'Cycle B',domain:'GSA',questType:'main',cadence:'once',startDate:'2026-08-10',dueDate:'2026-08-20',dependencies:['cycle-a']});assert(Deps.status(ctx.questById('cycle-a')).cycle,'dependency cycles must be detected');console.log('Calendar V5 strategic dependency regression passed');
