const fs=require('fs'),vm=require('vm'),assert=require('assert');
const localStorage={m:new Map(),getItem(k){return this.m.get(k)||null},setItem(k,v){this.m.set(k,String(v))}};
const state={view:'today',plannerDate:'2026-08-10',completed:{},xpLedger:{},bonusLedger:{},activityDates:[],customQuests:[],overrides:{},calendarV3:{workLedger:{}},calendarV5:{skippedDaily:{},sideQuestMeta:{lunch:{scheduleType:'flex-window',rigidity:'preferred',subtype:'necessary'},leisure:{scheduleType:'opportunistic',rigidity:'free',subtype:'leisure'}},sideQuestPacks:[],events:[],missionMeta:{},deferredUntil:{},manualPins:{},manualReplacements:{}},calendarExecutionV8:{history:{},dayCheckpoints:{'2026-08-11':{slots:[]}},actions:[]},dailyReviewV6:{version:1,reviewedThroughDate:'2026-08-10',pending:[],history:[]}};
const qMain={id:'main-old',title:'Entrega crítica',description:'Entrega estratégica atrasada.',domain:'GSA',questType:'main',cadence:'weekly',dueDate:'2026-08-11',xp:100,difficulty:5,priorityLevel:'critical'},qLunch={id:'lunch',title:'Almoçar',description:'Refeição necessária.',domain:'Pessoal',questType:'side',cadence:'daily',xp:10,difficulty:1},qLeisure={id:'leisure',title:'Assistir série',description:'Lazer opcional.',domain:'Pessoal',questType:'side',cadence:'daily',xp:5,difficulty:1};
state.calendarExecutionV8.dayCheckpoints['2026-08-11'].slots=[
 {sourceSlotId:'m1',workKey:'main-old@2026-08-10',questId:'main-old',qSnapshot:qMain,originDate:'2026-08-10',start:600,end:660,mainQuest:true,sideQuest:false,group:'GSA',deadline:'2026-08-11',sessionOnly:true,status:'pending'},
 {sourceSlotId:'s1',workKey:'lunch@2026-08-11',questId:'lunch',qSnapshot:qLunch,originDate:'2026-08-11',start:720,end:750,mainQuest:false,sideQuest:true,group:'Pessoal',sessionOnly:false,status:'pending'},
 {sourceSlotId:'l1',workKey:'leisure@2026-08-11',questId:'leisure',qSnapshot:qLeisure,originDate:'2026-08-11',start:1260,end:1320,mainQuest:false,sideQuest:true,group:'Pessoal',sessionOnly:false,status:'pending'}
];
let planCalls=0;const E={planDay:d=>{planCalls++;return{date:d,slots:d==='2026-08-12'?[{id:'m2',workKey:'main-old@2026-08-10',q:qMain,originDate:'2026-08-10',start:540,end:600,mainQuest:true,group:'GSA',deadline:'2026-08-11',sessionOnly:true}]:[],outsideCalendar:[]}},planWeek:d=>[],recordSession:s=>{state.calendarV3.workLedger[s.workKey]=(state.calendarV3.workLedger[s.workKey]||0)+(s.end-s.start);return true},invalidate(){this.invalidated=true}};
const campaigns=[{id:'camp-gsa',name:'GSA',groupId:'GSA',missionIds:['main-old']}],model={campaigns,missionMeta:{}};const B={groupForQuest:q=>q.domain,campaignForQuest:q=>q.id==='main-old'?campaigns[0]:null,model:()=>model};const D={model:()=>state.calendarV5,sideMeta:id=>state.calendarV5.sideQuestMeta[id]||null};
const ctx={console,Date,JSON,Math,Intl,localStorage,state,setTimeout:()=>0,clearTimeout:()=>{},requestAnimationFrame:()=>0,CustomEvent:function(t,i){this.type=t;this.detail=i?.detail},document:{hidden:false,visibilityState:'visible',addEventListener(){},getElementById(){return null},querySelectorAll(){return[]}},window:null,globalThis:null,render(){},toast(){},MyPerformanceCalendarModel:B,MyPerformanceCalendarDomain:D,MyPerformancePlannerEngine:E,MyPerformanceRoutine:{planDay:E.planDay}};ctx.window=ctx;ctx.globalThis=ctx;ctx.addEventListener=()=>{};ctx.iso=d=>{const x=new Date(d||Date.now());x.setMinutes(x.getMinutes()-x.getTimezoneOffset());return x.toISOString().slice(0,10)};ctx.dfrom=s=>new Date(`${s}T12:00:00`);ctx.addDays=(s,n)=>{const d=ctx.dfrom(s);d.setDate(d.getDate()+n);return ctx.iso(d)};ctx.diffDays=(a,b)=>Math.round((ctx.dfrom(b)-ctx.dfrom(a))/864e5);ctx.weekStart=s=>{const d=ctx.dfrom(s),n=(d.getDay()+6)%7;d.setDate(d.getDate()-n);return ctx.iso(d)};const qs=[qMain,qLunch,qLeisure];ctx.quests=()=>qs.concat(state.customQuests||[]);ctx.questById=id=>ctx.quests().find(q=>q.id===id);ctx.occurrenceKey=(q,d)=>q.cadence==='daily'?`${q.id}@${d}`:q.cadence==='weekly'?`${q.id}@${ctx.weekStart(d)}`:q.id;ctx.done=(q,d)=>!!state.completed[ctx.occurrenceKey(q,d)];ctx.addActivity=d=>{if(!state.activityDates.includes(d))state.activityDates.push(d)};ctx.saveState=()=>localStorage.setItem('state',JSON.stringify(state));
vm.createContext(ctx);vm.runInContext(fs.readFileSync('sp-clock-v6.js','utf8'),ctx);ctx.MyPerformanceClock.setTestNow('2026-08-12T12:00:00Z');vm.runInContext(fs.readFileSync('daily-review-v6.js','utf8'),ctx);
const R=ctx.MyPerformanceDailyReview;assert(R&&R.reviewRequired(),'review should use compact previous checkpoint');assert.strictEqual(planCalls,0,'building past backlog must not call Planner');const pending=R.pending();assert.strictEqual(pending.length,2,'opportunistic leisure must stay out of backlog');assert(pending.some(x=>x.questId==='main-old'));assert(pending.some(x=>x.questId==='lunch'));
for(const x of R.pending())R.decide(x.reviewId,'missed');assert(R.finalize());assert.strictEqual(state.plannerDate,'2026-08-12','finalize must return active date to today');assert(state.calendarV5.skippedDaily['2026-08-11']['lunch@2026-08-11']);const carry=state.customQuests.find(q=>q.sourceQuestId==='main-old');assert(carry&&carry.dueDate==='2026-08-11');assert(E.invalidated);const store=R.store();assert(Object.keys(store.snapshots).length<=3,'backlog snapshots must remain compact');
console.log('Daily lightweight backlog / no historical replanning regression passed');
