const fs=require('fs'),vm=require('vm'),assert=require('assert');
const localStorage={m:new Map(),getItem(k){return this.m.get(k)||null},setItem(k,v){this.m.set(k,String(v))}};const ctx={console,Date,JSON,Math,Intl,localStorage,setTimeout:()=>0,clearTimeout:()=>{},requestAnimationFrame:()=>0,confirm:()=>true,CustomEvent:function(t,i){this.type=t;this.detail=i?.detail},document:{visibilityState:'visible',addEventListener(){},getElementById(){return null},querySelectorAll(){return[]}},state:{view:'today',plannerDate:'2026-08-12',completed:{},xpLedger:{},bonusLedger:{},activityDates:[],customQuests:[],overrides:{},calendarV3:{workLedger:{}},calendarV5:{skippedDaily:{},sideQuestMeta:{lunch:{scheduleType:'flex-window',rigidity:'preferred',subtype:'necessary'},leisure:{scheduleType:'opportunistic',rigidity:'free',subtype:'leisure'}},sideQuestPacks:[],events:[],missionMeta:{},deferredUntil:{},manualPins:{},manualReplacements:{},revisions:[],decisionLog:[]},dailyReviewV6:{version:1,reviewedThroughDate:'2026-08-10',pending:[],history:[]}}};ctx.globalThis=ctx;ctx.window=ctx;ctx.addEventListener=()=>{};ctx.render=()=>{};ctx.toast=()=>{};ctx.iso=d=>{const x=new Date(d||Date.now());x.setMinutes(x.getMinutes()-x.getTimezoneOffset());return x.toISOString().slice(0,10)};ctx.dfrom=s=>new Date(`${s}T12:00:00`);ctx.addDays=(s,n)=>{const d=ctx.dfrom(s);d.setDate(d.getDate()+n);return ctx.iso(d)};ctx.diffDays=(a,b)=>Math.round((ctx.dfrom(b)-ctx.dfrom(a))/864e5);ctx.weekStart=s=>{const d=ctx.dfrom(s),n=(d.getDay()+6)%7;d.setDate(d.getDate()-n);return ctx.iso(d)};
const qs=[{id:'main-old',title:'Entrega crítica',description:'Entrega estratégica atrasada.',domain:'GSA',questType:'main',cadence:'weekly',dueDate:'2026-08-11',xp:100,difficulty:5,priorityLevel:'critical'},{id:'lunch',title:'Almoçar',description:'Refeição necessária.',domain:'Pessoal',questType:'side',cadence:'daily',xp:10,difficulty:1},{id:'leisure',title:'Assistir série',description:'Lazer opcional.',domain:'Pessoal',questType:'side',cadence:'daily',xp:5,difficulty:1}];ctx.quests=()=>qs.concat(ctx.state.customQuests||[]);ctx.questById=id=>ctx.quests().find(q=>q.id===id);ctx.occurrenceKey=(q,d)=>q.cadence==='daily'?`${q.id}@${d}`:q.cadence==='weekly'?`${q.id}@${ctx.weekStart(d)}`:q.id;ctx.done=(q,d)=>!!ctx.state.completed[ctx.occurrenceKey(q,d)];ctx.addActivity=d=>{if(!ctx.state.activityDates.includes(d))ctx.state.activityDates.push(d)};ctx.saveState=()=>localStorage.setItem('state',JSON.stringify(ctx.state));
const basePlans={
'2026-08-11':{date:'2026-08-11',slots:[{id:'m1',workKey:'main-old@2026-08-10',q:qs[0],originDate:'2026-08-10',start:600,end:660,mainQuest:true,group:'GSA',deadline:'2026-08-11',sessionOnly:true},{id:'s1',workKey:'lunch@2026-08-11',q:qs[1],originDate:'2026-08-11',start:720,end:750,sideQuest:true,group:'Pessoal'},{id:'l1',workKey:'leisure@2026-08-11',q:qs[2],originDate:'2026-08-11',start:1260,end:1320,sideQuest:true,group:'Pessoal'}],outsideCalendar:[]},
'2026-08-12':{date:'2026-08-12',slots:[{id:'m2',workKey:'main-old@2026-08-10',q:qs[0],originDate:'2026-08-10',start:540,end:600,mainQuest:true,group:'GSA',deadline:'2026-08-11',sessionOnly:true}],outsideCalendar:[]}}
const D={model:()=>ctx.state.calendarV5,sideMeta:id=>ctx.state.calendarV5.sideQuestMeta[id]||null};const campaigns=[{id:'camp-gsa',name:'GSA',groupId:'GSA',missionIds:['main-old']}];const B={groupForQuest:q=>q.domain,campaignForQuest:q=>q.id==='main-old'?campaigns[0]:null,model:()=>({campaigns,missionMeta:{}})};const E={planDay:d=>JSON.parse(JSON.stringify(basePlans[d]||{date:d,slots:[],outsideCalendar:[]})),planWeek:d=>[JSON.parse(JSON.stringify(basePlans[d]||{date:d,slots:[],outsideCalendar:[]}))],recordSession:(s)=>{ctx.state.calendarV3.workLedger[s.workKey]=Number(ctx.state.calendarV3.workLedger[s.workKey]||0)+(s.end-s.start);return true},invalidate(){this.invalidated=true}};ctx.MyPerformanceCalendarModel=B;ctx.MyPerformanceCalendarDomain=D;ctx.MyPerformancePlannerEngine=E;ctx.MyPerformanceRoutine={planDay:E.planDay};
vm.createContext(ctx);vm.runInContext(fs.readFileSync('sp-clock-v6.js','utf8'),ctx);ctx.MyPerformanceClock.setTestNow('2026-08-12T12:00:00Z');assert.strictEqual(ctx.MyPerformanceClock.today(),'2026-08-12');vm.runInContext(fs.readFileSync('daily-review-v6.js','utf8'),ctx);
const R=ctx.MyPerformanceDailyReview;assert(R&&R.reviewRequired(),'review should be required after day rollover');const pending=R.pending();assert.strictEqual(pending.length,2,'opportunistic leisure must not enter past-task review');assert(pending.some(x=>x.questId==='main-old'));assert(pending.some(x=>x.questId==='lunch'));
assert(!ctx.MyPerformancePlannerEngine.planDay('2026-08-12').slots.some(s=>s.workKey==='main-old@2026-08-10'),'past Main Quest must be held until review');
for(const x of R.pending())R.decide(x.reviewId,'missed');assert(R.finalize(),'finalize should succeed after all decisions');assert(!R.reviewRequired(),'review gate should clear');assert(ctx.state.calendarV5.skippedDaily['2026-08-11']['lunch@2026-08-11'],'missed daily Side Quest must expire');const carry=ctx.state.customQuests.find(q=>q.sourceQuestId==='main-old');assert(carry,'expired weekly Main Quest must create strategic carryover');assert.strictEqual(carry.dueDate,'2026-08-11','carryover must preserve original deadline');assert.strictEqual(carry.questType,'main');assert(ctx.MyPerformancePlannerEngine.invalidated,'planner must invalidate after review');
console.log('Daily rollover review / Sao Paulo clock regression passed');
