"use strict";
const assert=require('node:assert/strict'),fs=require('fs'),vm=require('vm');
const date='2026-08-10';
const qDone={id:'study-done',title:'Feita',domain:'Estudos',category:'Estudo',questType:'side',cadence:'daily',weekdays:[1],xp:20,durationMin:30};
const qDaily={id:'study-focus',title:'Estudar',domain:'Estudos',category:'Estudo',questType:'main',cadence:'daily',weekdays:[1,2,3,4,5],xp:40,durationMin:60};
const qRoutine={id:'personal-breakfast',title:'Café',domain:'Pessoal',category:'Rotina',questType:'side',cadence:'daily',weekdays:[1],fixedTime:true,essential:true,xp:10,durationMin:20};
const qOnce={id:'one-important',title:'Entrega',domain:'GSA',category:'Entrega',questType:'main',cadence:'once',startDate:date,dueDate:'2026-08-15',autoPlan:false,xp:80,durationMin:90};
const qWeekly={id:'weekly-followup',title:'Follow-up',domain:'Carreira',category:'Pipeline',questType:'main',cadence:'weekly',weekdays:[1,2,5],xp:50,durationMin:30};
const qAdaptive={id:'adaptive-parent-token',title:'Sessão automática',domain:'GSA',category:'Plano',questType:'main',cadence:'once',adaptiveSession:true,parentId:'parent',xp:20,durationMin:45};
const state={scheduler2:{syntheticDone:{}},dayPlanning:{minimumDone:{},sleepExtension:{}},liveCapacity:{releases:{}},customQuests:[],overrides:{},completed:{'study-done@2026-08-10':'2026-08-10T12:00:00.000Z'},adaptive:{schedule:[{questId:qAdaptive.id,parentId:'parent',date}]},timeTracking:{entries:[],activeId:''},view:'today',plannerDate:date};
const qs=[qDone,qDaily,qRoutine,qOnce,qWeekly,qAdaptive];
const dayNum=d=>new Date(d+'T12:00:00Z').getUTCDay();
const addDays=(d,n)=>{const x=new Date(d+'T12:00:00Z');x.setUTCDate(x.getUTCDate()+n);return x.toISOString().slice(0,10)};
const occurrenceKey=(q,d)=>q.cadence==='weekly'?`${q.id}@2026-08-10`:q.cadence==='monthly'?`${q.id}@${d.slice(0,7)}`:q.cadence==='daily'?`${q.id}@${d}`:q.id;
const done=(q,d)=>!!state.completed[occurrenceKey(q,d)];
const baseScheduled=(q,d)=>q.cadence==='daily'||q.cadence==='weekly'?(q.weekdays||[]).includes(dayNum(d)):q.cadence==='once'&&d>=(q.startDate||d);
const plan={date,slots:[qDone,qDaily,qRoutine,qOnce,qWeekly,qAdaptive].map((q,i)=>({q,originDate:date,start:480+i*70,end:510+i*70}))};
const body={appendChild(){},addEventListener(){}};
const head={appendChild(){}};
const document={body,head,getElementById(){return null},querySelector(){return null},querySelectorAll(){return[]},createElement(){return{id:'',textContent:'',appendChild(){}}}};
class MutationObserver{constructor(fn){this.fn=fn}observe(){}}
class CustomEvent{constructor(type,init){this.type=type;this.detail=init?.detail}}
let scheduled=baseScheduled,saves=0,renders=0;
const window={MyPerformanceRoutine:{planDay:()=>JSON.parse(JSON.stringify(plan)),missionNow:()=>({plan,current:null,next:null,minute:600})},MyPerformanceScheduler2:{summary:()=>({date,plan}),openRecalcCenter(){},pauseTracking(){}},addEventListener(){},dispatchEvent(){},MyPerformanceAdaptive:{recalculate(){}}};
const ctx={console,window,state,document,MutationObserver,CustomEvent,requestAnimationFrame:fn=>fn(),setTimeout:fn=>fn(),done,occurrenceKey,addDays,today:()=>date,fmt:d=>d,iso:d=>d.toISOString().slice(0,10),saveState:()=>saves++,render:()=>renders++,toast(){},quests:()=>qs};
Object.defineProperty(ctx,'scheduled',{get(){return scheduled},set(v){scheduled=v},configurable:true});
vm.createContext(ctx);vm.runInContext(fs.readFileSync('discard-day.js','utf8'),ctx);
const api=window.MyPerformanceDiscardDay;assert.ok(api);
assert.equal(api.isRelevant(qDaily),true);assert.equal(api.isRelevant(qRoutine),false);assert.equal(api.isRelevant(qAdaptive),true);
assert.equal(api.discardDay(date),true);
const rec=state.scheduler2.discardedDays[date];assert.equal(rec.relevantCount,4);
assert.equal(state.completed['study-done@2026-08-10'],'2026-08-10T12:00:00.000Z');
assert.equal(state.overrides['one-important'].startDate,'2026-08-11');
assert.equal(state.adaptive.schedule[0].date,'2026-08-11');
const carry=state.customQuests.find(q=>q.sourceQuestId==='study-focus');assert.ok(carry);assert.equal(carry.startDate,'2026-08-11');
assert.equal(state.customQuests.some(q=>q.sourceQuestId==='weekly-followup'),false,'weekly quest should use its next same-week occurrence');
assert.equal(ctx.scheduled(qDaily,date),false,'unfinished quests vanish from discarded day');
assert.equal(ctx.scheduled(qDone,date),true,'completed quests remain real on discarded day');
assert.equal(window.MyPerformanceRoutine.planDay(date).slots.length,0);
assert.ok(saves>=2);assert.ok(renders>=1);
console.log('Discard day behavior passed');
