const fs=require('fs');
const assert=require('assert');
const update=fs.readFileSync('pwa-update.js','utf8');
const sw=fs.readFileSync('sw.js','utf8');
const index=fs.readFileSync('index.html','utf8');
const version=JSON.parse(fs.readFileSync('version.json','utf8'));
assert.strictEqual(version.version,'2.0.0');
assert(index.includes('data-build="2.0.0"'));
assert(update.includes("navigator.serviceWorker.addEventListener('controllerchange'"),'client must listen for controller changes');
assert(update.includes('cacheBust(pendingVersion)'),'controller change must force a cache-busted navigation');
assert(update.includes('await applyUpdate(reg,remote.version)'),'remote version mismatch must auto-apply');
assert(sw.includes("const BUILD='2.0.0'"),'service worker build must be 2.0.0');
assert(sw.includes("const CACHE='my-performance-v2.0.0'"),'service worker cache must be 2.0.0');
assert(sw.includes('self.clients.matchAll({type:\'window\',includeUncontrolled:true})'),'activated worker must enumerate open windows');
assert(sw.includes('await client.navigate(u.toString())'),'activated worker must force stale open tabs onto the new document');
assert(sw.includes("fetch(event.request,{cache:'no-store'})"),'runtime assets must prefer a fresh network response');
console.log('PWA 2.0 stale-runtime forced refresh passed');
