const fs=require('fs'),vm=require('vm'),assert=require('assert');
const listeners={};const ctx={console,Date,JSON,Math,Intl,setTimeout:()=>0,clearTimeout:()=>{},CustomEvent:function(t,i){this.type=t;this.detail=i?.detail},localStorage:{m:new Map(),getItem(k){return this.m.get(k)||null},setItem(k,v){this.m.set(k,String(v))}},state:{completed:{},xpLedger:{},bonusLedger:{},activityDates:[],customQuests:[],overrides:{},questPlans:{},filters:{}}};ctx.globalThis=ctx;ctx.window=ctx;ctx.addEventListener=(t,f)=>(listeners[t]||(listeners[t]=[])).push(f);ctx.dispatchEvent=e=>(listeners[e.type]||[]).forEach(f=>f(e));ctx.iso=d=>{const x=new Date(d||Date.now());x.setMinutes(x.getMinutes()-x.getTimezoneOffset());return x.toISOString().slice(0,10)};ctx.dfrom=s=>new Date(`${s}T12:00:00`);ctx.today=()=> '2026-08-11';ctx.addDays=(s,n)=>{const d=ctx.dfrom(s);d.setDate(d.getDate()+n);return ctx.iso(d)};ctx.diffDays=(a,b)=>Math.round((ctx.dfrom(b)-ctx.dfrom(a))/864e5);ctx.weekStart=s=>{const d=ctx.dfrom(s),n=(d.getDay()+6)%7;d.setDate(d.getDate()-n);return ctx.iso(d)};ctx.saveState=()=>ctx.localStorage.setItem('my_performance_v1',JSON.stringify(ctx.state));
vm.createContext(ctx);for(const f of ['data.js','routine-data.js'])vm.runInContext(fs.readFileSync(f,'utf8'),ctx);ctx.quests=()=>ctx.QUEST_SEED.concat(ctx.state.customQuests||[]).map(q=>Object.assign({},q,ctx.state.overrides[q.id]||{})).filter(q=>!q.disabled);ctx.questById=id=>ctx.quests().find(q=>q.id===id);ctx.done=()=>false;ctx.hasEverDone=()=>false;
for(const f of ['calendar-model-v3.js','calendar-model-fastpath-v4.js','calendar-domain-v5.js','quest-audit-v6.js','quest-milestones-v6.js'])vm.runInContext(fs.readFileSync(f,'utf8'),ctx);
const B=ctx.MyPerformanceCalendarModel,D=ctx.MyPerformanceCalendarDomain,qs=ctx.quests();assert(B&&D&&ctx.MyPerformanceQuestAudit,'audit runtime missing');
assert(qs.every(q=>q.domain!=='Carreira'),'Carreira must be fully migrated');
for(const id of ['personal-sleep','personal-week-review','study-focus','study-q25','study-errors','study-basic','study-boss','study-postboss','career-pipeline','career-assets'])assert.strictEqual(ctx.questById(id)?.questType,'side',`${id} should be Side Quest`);
for(const q of qs.filter(q=>/^gsa-[cspe]\d+$/.test(q.id)))assert.strictEqual(q.questType,'main',`${q.id} GSA milestone must be Main Quest`);
for(const q of qs.filter(q=>/^gsa-r-/.test(q.id)&&q.id!=='gsa-r-bni'))assert.strictEqual(q.questType,'side',`${q.id} cadence must be Side Quest`);
for(const q of qs.filter(q=>/^study-(aug|sep|oct|nov|final)/.test(q.id))){assert.strictEqual(q.questType,'main',`${q.id} should be Main Quest`);assert.strictEqual(q.cadence,'once',`${q.id} fixed milestone must not repeat monthly`)}
for(const id of ['gsa-main-hacktown-2026','gsa-main-eva-launch','gsa-main-editais'])assert.strictEqual(ctx.questById(id)?.campaignContainer,true,`${id} must be campaign container`);
assert.strictEqual(ctx.questById('gsa-r-bni'),undefined,'legacy recurring BNI must be disabled because Event exists');
for(const q of qs.filter(q=>q.questType==='main'&&!q.specialCommitment&&!q.campaignContainer)){assert(B.campaignForQuest(q),`Main Quest without Campaign: ${q.id}`)}
for(const q of qs.filter(q=>q.questType!=='main'&&!q.specialCommitment)){const meta=D.sideMeta(q.id);assert(meta,`Side Quest without metadata: ${q.id}`);assert(meta.packId,`Side Quest without Pack: ${q.id}`);assert(D.pack(meta.packId),`Missing Pack ${meta.packId} for ${q.id}`)}
for(const id of ['campaign-transpetro-2026','campaign-gsa-operacao-2026'])assert(B.model().campaigns.some(c=>c.id===id),`missing ${id}`);
for(const id of ['pack-study-practice','pack-professional-development','pack-gsa-cadence'])assert(D.pack(id),`missing ${id}`);
console.log(`Quest audit passed: ${qs.filter(q=>q.questType==='main').length} Main Quests / ${qs.filter(q=>q.questType!=='main').length} Side Quests`);
