const fs=require('fs'),vm=require('vm'),assert=require('assert');
const code=fs.readFileSync('sidequest-priority-v11.js','utf8');
const meta={a:{packId:'p',maxRepeatsPerDay:2},b:{packId:'p',maxRepeatsPerDay:1}},pack={id:'p',name:'F',missionIds:['a','b']};let saves=0,invalidates=0;
const SQ={scoreBonus:()=>0,allowed:()=>true,packForItem:i=>pack};
const E={planDay:()=>({slots:[{sideQuest:true,workKey:'a@x::repeat-v11:2'}],outsideCalendar:[{kind:'side',key:'a@x::repeat-v11:3'}]}),planWeek:()=>[],invalidate:()=>invalidates++};
const D={sideMeta:id=>meta[id],pack:id=>id==='p'?pack:null,recordRevision:()=>{},log:()=>{}};
const ctx={console,state:{},saveState:()=>saves++,window:{MyPerformanceCalendarDomain:D,MyPerformanceSideQuestQuality:SQ,MyPerformancePlannerEngine:E,MyPerformanceRoutine:{}}};ctx.window.window=ctx.window;vm.createContext(ctx);vm.runInContext(code,ctx);const P=ctx.window.MyPerformanceSideQuestPriority;
const usage={};let a={kind:'side',q:{id:'a'},key:'a@x',remaining:60,policy:{packId:'p'}},b={kind:'side',q:{id:'b'},key:'b@x',remaining:60,policy:{packId:'p'}};
assert(SQ.scoreBonus(a,usage)>SQ.scoreBonus(b,usage),'Filler order must influence priority score');
assert(SQ.allowed(a,usage));SQ.record(a,30,usage);assert(a.key.includes('::repeat-v11:2'),'first execution should keep a second planner occurrence eligible');assert(SQ.allowed(a,usage));SQ.record(a,30,usage);assert(!SQ.allowed(a,usage),'max 2/day must stop a third execution');
let p=E.planDay('x');assert.strictEqual(p.slots[0].workKey,'a@x');assert.strictEqual(p.outsideCalendar[0].key,'a@x','public Planner keys must stay canonical');
assert(P.reorderFiller('p',['b','a']));assert.deepStrictEqual(pack.missionIds,['b','a']);assert(saves>0&&invalidates>0);
P.setRepeats('b',3);assert.strictEqual(meta.b.maxRepeatsPerDay,3);
console.log('Filler order and Side Quest repeat policy V11 passed');
