const fs=require('fs'),vm=require('vm'),assert=require('assert');
let minute=1140,date='2026-08-11';const listeners={};
const qA={id:'a',title:'Tarefa 15h',domain:'GSA',questType:'main',cadence:'once',xp:20},qB={id:'b',title:'Tarefa 16h',domain:'GSA',questType:'main',cadence:'once',xp:20},qC={id:'c',title:'Bloco 19–21',domain:'Estudos',questType:'main',cadence:'once',xp:30},qFill={id:'fill',title:'Preenchimento futuro',domain:'Estudos',questType:'side',cadence:'once',xp:10};const all=[qA,qB,qC,qFill];
const state={completed:{},xpLedger:{},bonusLedger:{},activityDates:[],calendarV5:{skippedDaily:{},deferredUntil:{},manualPins:{},manualReplacements:{}}};
const Clock={today:()=>date,minutesNow:()=>minute,time:()=>`${String(Math.floor(minute/60)).padStart(2,'0')}:${String(minute%60).padStart(2,'0')}`,stamp:()=>`${date}T${String(Math.floor(minute/60)).padStart(2,'0')}:${String(minute%60).padStart(2,'0')}:00-03:00`};
const ctx={console,Date,JSON,Math,state,CustomEvent:function(t,d){this.type=t;this.detail=d?.detail},document:{visibilityState:'visible',addEventListener(){}},localStorage:{getItem(){return null},setItem(){}},setTimeout:()=>0,requestAnimationFrame:fn=>fn()};ctx.window=ctx;ctx.globalThis=ctx;ctx.MyPerformanceClock=Clock;ctx.addEventListener=(t,f)=>(listeners[t]||(listeners[t]=[])).push(f);ctx.dispatchEvent=e=>(listeners[e.type]||[]).forEach(f=>f(e));ctx.questById=id=>all.find(q=>q.id===id);ctx.occurrenceKey=(q,d)=>q.id;ctx.dependencyStatus=()=>({locked:false});ctx.hasEverDone=()=>false;ctx.addActivity=d=>{if(!state.activityDates.includes(d))state.activityDates.push(d)};ctx.toast=()=>{};ctx.saveState=()=>ctx.dispatchEvent(new ctx.CustomEvent('my-performance-state-saved',{detail:state}));ctx.weekStart=d=>d;ctx.addDays=d=>d;
let events=[];const D={events:()=>events,model:()=>state.calendarV5};ctx.MyPerformanceCalendarDomain=D;
const toMin=t=>{const [h,m]=String(t).split(':').map(Number);return h*60+m},toTime=n=>`${String(Math.floor(n/60)%24).padStart(2,'0')}:${String(n%60).padStart(2,'0')}`;
function blocked(s,e){return D.events().some(x=>{const a=toMin(x.start),b=toMin(x.end);return s<b&&e>a})}function slot(q,s,e){return{id:`slot-${q.id}`,q,originDate:date,start:s,end:e,movable:true,mainQuest:q.questType==='main',sideQuest:q.questType!=='main',sessionOnly:q.questType==='main',group:q.domain,workKey:`${q.id}@x`,windowId:q.domain==='GSA'?'gsa':'study',reason:'planejado'}}
let invalidations=0;const E={toTime,toMin,invalidate(){invalidations++},emptyWindows:p=>[],recordSession(s){state.ledger=state.ledger||{};state.ledger[s.workKey]=(state.ledger[s.workKey]||0)+(s.end-s.start);ctx.saveState();return true},skipSlot(s){state.skipped=state.skipped||{};state.skipped[s.workKey]=true;ctx.saveState();return true},planDay(){const out=[];if(!state.completed.a&&!blocked(900,960))out.push(slot(qA,900,960));if(!state.completed.b&&!state.skipped?.['b@x']&&!blocked(960,1020))out.push(slot(qB,960,1020));if(!state.completed.c&&!blocked(1140,1260))out.push(slot(qC,1140,1260));if(state.completed.c&&!blocked(1200,1260))out.push(slot(qFill,1200,1260));return{date,windows:[{id:'gsa',start:540,end:1080},{id:'study',start:1140,end:1320}],slots:out,outsideCalendar:[]}}};ctx.MyPerformancePlannerEngine=E;ctx.MyPerformanceRoutine={};
vm.createContext(ctx);vm.runInContext(fs.readFileSync('temporal-execution-v8.js','utf8'),ctx);const T=ctx.MyPerformanceTemporalExecution;assert(T,'Temporal execution API must load');
let p=T.planDay(date);assert(p.slots.some(s=>s.q.id==='a'&&s.start===900),'15h planned block must remain visible at 19h');assert(p.slots.some(s=>s.q.id==='b'&&s.start===960),'16h planned block must remain visible at 19h');
let a=p.slots.find(s=>s.q.id==='a');let r=T.completeMission(a,date);assert.strictEqual(r.releaseMinutes,0,'past completion must release zero minutes');p=T.planDay(date);assert(p.slots.some(s=>s.q.id==='a'&&s.executionStatus==='completed'),'past completed card must remain frozen');assert(p.slots.some(s=>s.q.id==='b'&&s.executionHistory),'other elapsed blocks must remain as history');assert(!p.slots.some(s=>!s.executionHistory&&s.start<1140),'Planner must never create replacement work in the past');
let b=p.slots.find(s=>s.q.id==='b');r=T.skipSlot(b,date);assert.strictEqual(r.releaseMinutes,0,'past missed block must release zero past capacity');p=T.planDay(date);assert(p.slots.some(s=>s.q.id==='b'&&s.executionStatus==='missed'),'missed 16h card must remain frozen');
minute=1200;T.refreshNow();p=T.planDay(date);let c=p.slots.find(s=>s.q.id==='c');assert(c,'active 19–21 block must still exist at 20h');r=T.completeMission(c,date);assert.strictEqual(r.releaseMinutes,60,'completion at 20h must release only 20–21');p=T.planDay(date);assert(p.slots.some(s=>s.q.id==='c'&&s.executionStatus==='completed'&&s.start===1140&&s.end===1260),'original 19–21 block must remain as completed history');assert(p.slots.some(s=>s.q.id==='fill'&&s.start===1200&&s.end===1260&&!s.executionHistory),'released 20–21 must be available for future allocation');assert(!p.slots.some(s=>!s.executionHistory&&s.start<1200),'no post-action dynamic work may be allocated before now');
assert(state.completed.a&&state.completed.c,'mission completion must persist actual Quest completion');assert(T.history(date).some(x=>x.actualAt?.includes('20:00')),'actual completion time must be stored using Sao Paulo authority');console.log('Temporal Execution V8 immutable-past and early-release regression passed');
