const fs=require('fs'),vm=require('vm'),assert=require('assert');
const code=fs.readFileSync('temporal-consistency-v11.js','utf8');
let baseCalls=0;
const plans={'2026-08-12':{date:'2026-08-12',slots:[{id:'today',q:{id:'q'},start:600,end:660}],outsideCalendar:[]}};
const E={planDay:d=>{baseCalls++;return JSON.parse(JSON.stringify(plans[d]||{date:d,slots:[{id:'fresh-past'}],outsideCalendar:[{key:'retro'}]}))},planWeek:()=>[],emptyWindows:()=>[{start:360,end:400}],missionNow:()=>({})};
const ctx={console,state:{calendarV3:{discardedDays:{}}},weekStart:d=>d,addDays:(d,n)=>d,window:{MyPerformanceClock:{today:()=> '2026-08-12',minutesNow:()=>720},MyPerformancePlannerEngine:E,MyPerformanceRoutine:{}}};ctx.window.window=ctx.window;vm.createContext(ctx);vm.runInContext(code,ctx);
let p=E.planDay('2026-08-11');
assert.strictEqual(baseCalls,0,'past dates must not invoke the Planner at all');
assert.strictEqual(p.lightweightPast,true);assert.strictEqual(p.plannerSkipped,true);assert.strictEqual(p.slots.length,0);assert.strictEqual(p.outsideCalendar.length,0);assert.strictEqual(E.emptyWindows('2026-08-11').length,0);
p=E.planDay('2026-08-12');assert.strictEqual(baseCalls,1,'today remains the hot Planner date');assert(p.slots.some(x=>x.id==='today'));
ctx.state.calendarV3.discardedDays['2026-08-12']={at:'now'};p=E.planDay('2026-08-12');assert.strictEqual(p.discarded,true);assert.strictEqual(p.outsideCalendar.length,0);
console.log('Temporal V12 hot-today / lightweight-past semantics passed');
