const fs=require('fs'),vm=require('vm'),assert=require('assert');
let minute=1412,date='2026-08-11';const listeners={};
const q1={id:'q1',title:'Histórico 06:00',domain:'Pessoal',questType:'side',cadence:'daily'},q2={id:'q2',title:'Histórico 06:30',domain:'Pessoal',questType:'side',cadence:'daily'},q3={id:'q3',title:'Histórico 06:45',domain:'Pessoal',questType:'side',cadence:'daily'},q4={id:'q4',title:'Bloco 19–21',domain:'Estudos',questType:'main',cadence:'once'};const all=[q1,q2,q3,q4];
const state={completed:{},xpLedger:{},bonusLedger:{},activityDates:[],calendarV5:{skippedDaily:{},deferredUntil:{},manualPins:{},manualReplacements:{}}};
const Clock={today:()=>date,minutesNow:()=>minute,time:()=>`${String(Math.floor(minute/60)).padStart(2,'0')}:${String(minute%60).padStart(2,'0')}`,stamp:()=>`${date}T${String(Math.floor(minute/60)).padStart(2,'0')}:${String(minute%60).padStart(2,'0')}:00-03:00`};
const ctx={console,Date,JSON,Math,state,CustomEvent:function(t,d){this.type=t;this.detail=d?.detail},document:{visibilityState:'visible',addEventListener(){}},setTimeout:()=>0,requestAnimationFrame:fn=>fn()};ctx.window=ctx;ctx.globalThis=ctx;ctx.MyPerformanceClock=Clock;ctx.addEventListener=(t,f)=>(listeners[t]||(listeners[t]=[])).push(f);ctx.dispatchEvent=e=>(listeners[e.type]||[]).forEach(f=>f(e));ctx.questById=id=>all.find(q=>q.id===id);ctx.occurrenceKey=q=>q.id;ctx.dependencyStatus=()=>({locked:false});ctx.hasEverDone=()=>false;ctx.addActivity=()=>{};ctx.toast=()=>{};ctx.saveState=()=>{};ctx.weekStart=d=>d;ctx.addDays=d=>d;
const D={events:()=>[],model:()=>state.calendarV5};ctx.MyPerformanceCalendarDomain=D;
const toTime=n=>`${String(Math.floor(n/60)%24).padStart(2,'0')}:${String(n%60).padStart(2,'0')}`,toMin=t=>{const [h,m]=String(t).split(':').map(Number);return h*60+m};
const overlap=(a,b)=>a.start<b.end&&a.end>b.start;function baseEmpty(p){const out=[];for(const w of p.windows||[]){const xs=(p.slots||[]).filter(s=>overlap(s,w)).sort((a,b)=>a.start-b.start);let cur=w.start;for(const s of xs){if(s.start>cur&&s.start-cur>=10)out.push({windowId:w.id,label:w.label||w.id,start:cur,end:s.start,minutes:s.start-cur});cur=Math.max(cur,s.end)}if(w.end-cur>=10)out.push({windowId:w.id,label:w.label||w.id,start:cur,end:w.end,minutes:w.end-cur})}return out}
const mk=(q,start,end)=>({id:`${q.id}-${start}`,q,originDate:date,start,end,movable:true,mainQuest:q.questType==='main',sideQuest:q.questType!=='main',sessionOnly:q.questType==='main',group:q.domain,workKey:`${q.id}@${date}`,windowId:start<600?'health':'study'});
const E={toTime,toMin,invalidate(){},emptyWindows:baseEmpty,recordSession(){return true},skipSlot(){return true},planDay(){const windows=[{id:'health',start:360,end:540,label:'Acordar com Saúde'},{id:'study',start:1140,end:1260,label:'Estudo'}],slots=[mk(q1,360,390),mk(q2,390,405),mk(q3,405,420)];if(!state.completed.q4)slots.push(mk(q4,1140,1260));return{date,windows,slots,outsideCalendar:[]}}};ctx.MyPerformancePlannerEngine=E;ctx.MyPerformanceRoutine={};
vm.createContext(ctx);vm.runInContext(fs.readFileSync('temporal-execution-v8.js','utf8'),ctx);const T=ctx.MyPerformanceTemporalExecution;assert(T);
let p=T.planDay(date),g=ctx.MyPerformancePlannerEngine.emptyWindows(p);assert.strictEqual(g.length,0,'At 23:32 no elapsed gap may be exposed as available capacity');
minute=1200;T.refreshNow();p=T.planDay(date);const active=p.slots.find(s=>s.q.id==='q4');assert(active,'19–21 block must exist at 20:00');const r=T.completeMission(active,date);assert.strictEqual(r.releaseMinutes,60);p=T.planDay(date);g=ctx.MyPerformancePlannerEngine.emptyWindows(p);const released=g.find(x=>x.start===1200&&x.end===1260);assert(released,'Only 20:00–21:00 must become free after early completion');assert(!g.some(x=>x.start<1200),'No free segment before NOW may be exposed');
console.log('Temporal gap boundary regression passed');
