const fs=require('fs');
const assert=require('assert');
const version=JSON.parse(fs.readFileSync('version.json','utf8')).version;
const index=fs.readFileSync('index.html','utf8');
const sw=fs.readFileSync('sw.js','utf8');
const runtime=fs.readFileSync('calendar-runtime-v3.js','utf8');
assert(index.includes(`data-build="${version}"`),'index.html build must match version.json');
assert(sw.includes(`my-performance-v${version}`),'service-worker cache must match version.json');
assert(runtime.includes('document.documentElement.dataset.build'),'visible calendar build must derive from the shell build');
console.log(`Version consistency passed for ${version}`);
