const fs=require('fs'),assert=require('assert'),vm=require('vm');
const index=fs.readFileSync('index.html','utf8'),wake=fs.readFileSync('wake-time-ui-v6.js','utf8'),quant=fs.readFileSync('quantitative-mainquests-v6.js','utf8'),fragment=fs.readFileSync('fragment-progress-v6.js','utf8'),css=fs.readFileSync('ui-polish-v6.css','utf8'),sw=fs.readFileSync('sw.js','utf8'),version=require('../version.json');
assert(index.includes(`data-build="${version.version}"`));
for(const a of ['quantitative-mainquests-v6.js','wake-time-ui-v6.js','fragment-progress-v6.js','ui-polish-v6.css'])assert(index.includes(a),`missing ${a}`);
assert(index.indexOf('quantitative-mainquests-v6.js')<index.indexOf('planner-engine-v5.js'),'quantitative policy must load before Planner');
assert(index.indexOf('day-frame-v5.js')<index.indexOf('wake-time-ui-v6.js'),'wake UI must enhance Day Frame');
assert(index.indexOf('mission-context-v5.js')<index.indexOf('fragment-progress-v6.js'),'fragment V6 must refine mission context');
for(const t of ['☀ Acordei','type="time"','Que horas você acordou?','Clock.minutesNow','não pode estar no futuro','Frame.wakeNow'])assert(wake.includes(t),`wake contract missing ${t}`);
for(const t of ['.pill,.tag,.type-badge','.mission-fragment-progress','justify-content:center','text-align:center'])assert(css.includes(t),`pill centering missing ${t}`);
for(const t of ['Bloco <b>','concluídos','quantityDone','Meta operacional'])assert(fragment.includes(t),`fragment contract missing ${t}`);
const ctx={window:{},console};ctx.window=ctx;ctx.MyPerformanceCalendarDomain={missionPolicy:()=>({})};vm.createContext(ctx);vm.runInContext(quant,ctx);
const aug=ctx.MyPerformanceCalendarDomain.missionPolicy({id:'study-aug-volume'}),sep=ctx.MyPerformanceCalendarDomain.missionPolicy({id:'study-sep-volume'}),oct=ctx.MyPerformanceCalendarDomain.missionPolicy({id:'study-oct-volume'});
assert.strictEqual(aug.quantityTarget,600);assert.strictEqual(aug.quantityPerBlock,40);assert.strictEqual(aug.totalBlocks,15);assert.strictEqual(aug.idealSessionMin,90);assert.strictEqual(aug.effortLikelyMin,1350);
assert.strictEqual(sep.totalBlocks,25);assert.strictEqual(oct.totalBlocks,30);
for(const a of ['./quantitative-mainquests-v6.js','./wake-time-ui-v6.js','./fragment-progress-v6.js','./ui-polish-v6.css'])assert(sw.includes(a),`PWA missing ${a}`);
assert(sw.includes(`BUILD='${version.version}'`));assert(sw.includes(`CACHE='my-performance-v${version.version}'`));
console.log(`Wake-time, centered pills and quantitative fragment regression passed for ${version.version}`);
